export const Kanji = [
    { Id: '曜', SinoVietnamese: 'DIỆU', On: 'ヨウ', Kun: 'よう' },

    { Id: '魚', SinoVietnamese: 'NGƯ', On: 'ギョ', Kun: 'さかな' },
    { Id: '肉', SinoVietnamese: 'NHỤC', On: '二ク', Kun: 'にく' },
    { Id: '卵', SinoVietnamese: 'NOÃN', On: 'タマゴ', Kun: 'たまご' },

    { Id: '月', SinoVietnamese: 'NGUYỆT', On: 'ゲツ、ガツ', Kun: 'つき' },
    { Id: '火', SinoVietnamese: 'HỎA', On: 'カ', Kun: 'ひ、び' },
    { Id: '水', SinoVietnamese: 'THỦY', On: 'スイ', Kun: 'みず' },
    { Id: '木', SinoVietnamese: 'MỘC', On: 'モク、ボク', Kun: 'き、こ' },
    { Id: '金', SinoVietnamese: 'KIM', On: 'キン、コン', Kun: 'かね、がね' },
    { Id: '土', SinoVietnamese: 'THỔ', On: 'ト、ド', Kun: 'つち' },
    { Id: '日', SinoVietnamese: 'NHẬT', On: 'ニチ、ジツ', Kun: 'ひ、び、か' },

    { Id: '大', SinoVietnamese: 'ĐẠI', On: 'ダイ、タイ', Kun: 'おお' },
    { Id: '小', SinoVietnamese: 'TIỂU', On: 'ショウ', Kun: 'ちい、こ、お' },
    { Id: '新', SinoVietnamese: 'TÂN', On: 'シン', Kun: 'あたら、あら、にい' },
    { Id: '古', SinoVietnamese: 'CỔ', On: 'コ', Kun: 'ふる' },
    { Id: '時', SinoVietnamese: 'THỜI', On: 'ジ', Kun: 'とき' },
    { Id: '分', SinoVietnamese: 'PHÂN', On: 'フン、プン、ブン、ブ', Kun: 'わ' },
    { Id: '半', SinoVietnamese: 'BÁN', On: 'ハン', Kun: 'なか' },

    { Id: '言', SinoVietnamese: 'NGÔN', On: 'ゴン、ゲン', Kun: 'い、こと' },
    { Id: '話', SinoVietnamese: 'THOẠI', On: 'ワ', Kun: 'はな、はなし' },
    { Id: '読', SinoVietnamese: 'ĐỘC', On: 'ドク、トク、トウ', Kun: 'よ' },
    { Id: '見', SinoVietnamese: 'KIẾN', On: 'ケン', Kun: 'み' },
    { Id: '聞', SinoVietnamese: 'VĂN, VẤN', On: 'ブン、モン', Kun: 'き' },
    { Id: '書', SinoVietnamese: 'THƯ', On: 'ショ', Kun: 'か、が' },

    { Id: '一', SinoVietnamese: 'NHẤT', On: 'イチ、イツ', Kun: 'ひと' },
    { Id: '二', SinoVietnamese: 'NHỊ', On: '二、ジ', Kun: 'ふた' },
    { Id: '三', SinoVietnamese: 'TAM', On: 'サン', Kun: 'み、みっ' },
    { Id: '四', SinoVietnamese: 'TỨ', On: 'シ', Kun: 'よ、よん、よっ' },
    { Id: '五', SinoVietnamese: 'NGŨ', On: 'ゴ、ゴウ', Kun: 'いつ' },
    { Id: '六', SinoVietnamese: 'LỤC', On: 'ロク、リク', Kun: 'む、むっ' },
    { Id: '七', SinoVietnamese: 'THẤT', On: 'シチ、シツ', Kun: 'なな、なの' },
    { Id: '八', SinoVietnamese: 'BÁT', On: 'ハチ', Kun: 'や、やっ、よう' },
    { Id: '九', SinoVietnamese: 'CỬU', On: 'キュウ、ク', Kun: 'ここの' },
    { Id: '十', SinoVietnamese: 'THẬP', On: 'ジュウ、ジッ、ジュッ', Kun: 'とお、と' },
    { Id: '年', SinoVietnamese: 'NIÊN', On: 'ネン', Kun: 'とし' },

    { Id: '東', SinoVietnamese: 'ĐÔNG', On: 'トウ', Kun: 'ひがし' },
    { Id: '西', SinoVietnamese: 'TÂY', On: 'セイ、サイ、ゼイ', Kun: 'にし' },
    { Id: '南', SinoVietnamese: 'NAM', On: 'ナン、ナ', Kun: 'みなみ' },
    { Id: '北', SinoVietnamese: 'BẮC', On: 'ホク、ホッ、ボク', Kun: 'きた' },
    { Id: '口', SinoVietnamese: 'KHẨU', On: 'コウ、ク', Kun: 'くち、ぐち' },

    { Id: '買', SinoVietnamese: 'MÃI', On: 'バイ', Kun: 'か' },
    { Id: '百', SinoVietnamese: 'BÁCH', On: 'ヒャク、ビャク', Kun: 'もも' },
    { Id: '千', SinoVietnamese: 'THIÊN', On: 'セン', Kun: 'ち' },
    { Id: '万', SinoVietnamese: 'VẠN', On: 'マン、バン', Kun: 'よろず' },
    { Id: '円', SinoVietnamese: 'VIÊN', On: 'エン', Kun: 'まる、まど、まろ' },
    { Id: '物', SinoVietnamese: 'VẬT', On: 'ブツ', Kun: 'もの' },

    { Id: '行', SinoVietnamese: 'HÀNH', On: 'コウ、ギョウ、アン', Kun: 'い、ゆ、おこな' },
    { Id: '来', SinoVietnamese: 'LAI', On: 'ライ、タイ', Kun: 'く、き、こ、きた' },
    { Id: '会', SinoVietnamese: 'HỘI', On: 'カイ、エ', Kun: 'あ' },
    { Id: '休', SinoVietnamese: 'HƯU', On: 'キュウ', Kun: 'やす' },
    { Id: '本', SinoVietnamese: 'BỔN', On: 'ホン', Kun: 'もと' },
    { Id: '京', SinoVietnamese: 'KINH', On: 'キョウ、ケイ', Kun: 'きょう、けい' },

    { Id: '私', SinoVietnamese: 'TƯ', On: 'シ', Kun: 'わたし、わたくし' },
    { Id: '父', SinoVietnamese: 'PHỤ', On: 'フ', Kun: 'ちち' },
    { Id: '母', SinoVietnamese: 'MẪU', On: 'ボ', Kun: 'はは、も' },
    { Id: '子', SinoVietnamese: 'TỬ', On: 'シ、ス、ツ', Kun: 'こ、ね' },
    { Id: '男', SinoVietnamese: 'NAM', On: 'ダン、ナン', Kun: 'おとこ' },
    { Id: '女', SinoVietnamese: 'NỮ', On: 'ジョ、ニョ、ニョウ', Kun: 'おんな、め' },
    { Id: '人', SinoVietnamese: 'NHÂN', On: 'ジン、ニン', Kun: 'ひと、り、と' },
    { Id: '何', SinoVietnamese: 'HÀ', On: 'カ', Kun: 'なに、なん' },

    { Id: '好', SinoVietnamese: 'HẢO', On: 'コウ', Kun: 'この、す、よ、い' },
    { Id: '語', SinoVietnamese: 'NGỮ', On: 'ゴ', Kun: 'かた' },
    { Id: '外', SinoVietnamese: 'NGOẠI', On: 'ガイ、ゲ', Kun: 'そと、ほか、はず、と' },
    { Id: '国', SinoVietnamese: 'QUỐC', On: 'コク', Kun: 'くに' },

    { Id: '春', SinoVietnamese: 'XUÂN', On: 'シュン', Kun: 'はる' },
    { Id: '夏', SinoVietnamese: 'HẠ', On: 'カ、ガ、ゲ', Kun: 'なつ' },
    { Id: '秋', SinoVietnamese: 'THU', On: 'シュウ', Kun: 'あき、とき' },
    { Id: '冬', SinoVietnamese: 'ĐÔNG', On: 'トウ', Kun: 'ふゆ' },
    { Id: '今', SinoVietnamese: 'KIM', On: 'コン、キン', Kun: 'いま' },
    { Id: '花', SinoVietnamese: 'HOA', On: 'カ、ケ', Kun: 'はな' },
    { Id: '海', SinoVietnamese: 'HẢI', On: 'カイ、ゲ', Kun: 'うみ' },////////////////////////////////////////////////////////////////////
    { Id: '山', SinoVietnamese: 'SƠN, SAN', On: 'サン、セン', Kun: 'やま' },
    { Id: '川', SinoVietnamese: 'XUYÊN', On: 'セン', Kun: 'かわ' },

    { Id: '天', SinoVietnamese: 'THIÊN', On: 'テン', Kun: 'あまつ、あめ、あま' },
    { Id: '気', SinoVietnamese: 'KHÍ', On: 'キ、ケ', Kun: 'き' },
    { Id: '晴', SinoVietnamese: 'TÌNH', On: 'セイ', Kun: 'は、ば' },
    { Id: '雨', SinoVietnamese: 'VŨ', On: 'ウ', Kun: 'あめ' },
    { Id: '雪', SinoVietnamese: 'TUYẾT', On: 'セツ', Kun: 'ゆき' },
    { Id: '雲', SinoVietnamese: 'VÂN', On: 'ウン', Kun: 'くも、ぐも' },
    { Id: '風', SinoVietnamese: 'PHONG', On: 'フウ、フ', Kun: 'かぜ、かざ' },
    { Id: '空', SinoVietnamese: 'KHÔNG, KHỐNG', On: 'クウ', Kun: 'そら、あ、から、す、むな' },

    { Id: '町', SinoVietnamese: 'ĐINH', On: 'チョウ', Kun: 'まち' },
    { Id: '店', SinoVietnamese: 'ĐIẾM', On: 'テン', Kun: 'みせ、たな' },
    { Id: '多', SinoVietnamese: 'ĐA', On: 'タ', Kun: 'おお、まさ' },
    { Id: '少', SinoVietnamese: 'THIẾU, THIỂU', On: 'ショウ', Kun: 'すこ、すく' },
    { Id: '高', SinoVietnamese: 'CAO', On: 'コウ', Kun: 'たか' },
    { Id: '安', SinoVietnamese: 'AN', On: 'アン', Kun: 'やす' },
    { Id: '広', SinoVietnamese: 'QUẢNG', On: 'コウ', Kun: 'ひろ' },

    { Id: '道', SinoVietnamese: 'ĐẠO, ĐÁO', On: 'ドウ、トウ', Kun: 'みち' },
    { Id: '通', SinoVietnamese: 'THÔNG', On: 'ツウ、ツ', Kun: 'とお、どお、かよ' },
    { Id: '右', SinoVietnamese: 'HỮU', On: 'ウ、ユウ', Kun: 'みぎ' },
    { Id: '左', SinoVietnamese: 'TẢ', On: 'サ、シャ', Kun: 'ひだり' },
    { Id: '赤', SinoVietnamese: 'XÍCH', On: 'セキ、シャク', Kun: 'あか' },
    { Id: '青', SinoVietnamese: 'THANH', On: 'セイ、ショウ', Kun: 'あお' },
    { Id: '黒', SinoVietnamese: 'HẮC', On: 'コク', Kun: 'くろ' },
    { Id: '白', SinoVietnamese: 'BẠCH', On: 'ハク、ビャク', Kun: 'しろ、しら' },

    { Id: '間', SinoVietnamese: 'GIAN', On: 'カン、ケン', Kun: 'あいだ、ま' },
    { Id: '場', SinoVietnamese: 'TRÀNG, TRƯỜNG', On: 'ジョウ、チョウ', Kun: 'ば' },
    { Id: '所', SinoVietnamese: 'SỞ', On: 'ショ', Kun: 'ところ、どころ、とこ' },
    { Id: '駅', SinoVietnamese: 'DỊCH', On: 'エキ', Kun: 'えき' },
    { Id: '出', SinoVietnamese: 'XUẤT', On: 'シュツ、スイ', Kun: 'で、だ' },
    { Id: '待', SinoVietnamese: 'ĐÃI', On: 'タイ', Kun: 'ま' },
    { Id: '止', SinoVietnamese: 'CHỈ', On: 'シ', Kun: 'と' },

    { Id: '事', SinoVietnamese: 'SỰ', On: 'ジ、ズ', Kun: 'こと' },
    { Id: '仕', SinoVietnamese: 'SĨ', On: 'シ、ジ', Kun: 'つか' },
    { Id: '前', SinoVietnamese: 'TIỀN', On: 'ゼン', Kun: 'まえ' },
    { Id: '後', SinoVietnamese: 'HẬU', On: 'ゴ、コウ', Kun: 'のち、うし、あと、おく' },////////////////////////////////////////////////////////////////////
    { Id: '朝', SinoVietnamese: 'TRIỀU', On: 'チョウ', Kun: 'あさ' },
    { Id: '昼', SinoVietnamese: 'TRÚ', On: 'チュウ', Kun: 'ひる' },
    { Id: '夜', SinoVietnamese: 'DẠ', On: 'ヤ', Kun: 'よ、よる' },
    { Id: '乗', SinoVietnamese: 'THỪA', On: 'ジョウ、ショウ', Kun: 'の' },

    { Id: '学', SinoVietnamese: 'HỌC', On: 'ガク', Kun: 'まな' },
    { Id: '校', SinoVietnamese: 'HIỆU', On: 'コウ、キョウ', Kun: 'こう、きょう、かせ' },////////////////////////////////////////////////////////////////////
    { Id: '先', SinoVietnamese: 'TIÊN', On: 'セン', Kun: 'さき、ま' },
    { Id: '生', SinoVietnamese: 'SINH', On: 'セイ、ショウ', Kun: 'い、う、お、は、き、なま、な、む' },
    { Id: '勉', SinoVietnamese: 'MIỄN', On: 'ベン', Kun: 'つと' },
    { Id: '強', SinoVietnamese: 'CƯỠNG', On: 'キョウ、ゴウ', Kun: 'つよ' },
    { Id: '文', SinoVietnamese: 'VĂN', On: 'ブン、モン', Kun: 'ふみ、あや' },
    { Id: '化', SinoVietnamese: 'HÓA', On: 'カ、ケ', Kun: 'ば、ふ、け' },
    { Id: '音', SinoVietnamese: 'ÂM', On: 'オン、イン、ノン', Kun: 'おと、ね' },
    { Id: '楽', SinoVietnamese: 'LẠC', On: 'ガク、ラク、ゴウ', Kun: 'たの、この' },
    { Id: '留', SinoVietnamese: 'LƯU', On: 'リュウ、ル', Kun: 'と、とど、るうぶる' },
    { Id: '旅', SinoVietnamese: 'LỮ', On: 'リョ', Kun: 'たび' },
    { Id: '友', SinoVietnamese: 'HỮU', On: 'ユウ', Kun: 'とも' },
    { Id: '達', SinoVietnamese: 'ĐẠT', On: 'タツ、ダ', Kun: 'たち' },

    { Id: '酒', SinoVietnamese: 'TỬU', On: 'シュウ', Kun: 'さけ、さか' },
    { Id: '作', SinoVietnamese: 'TÁC', On: 'サク、サ', Kun: 'つく、づく' },
    { Id: '茶', SinoVietnamese: 'TRÀ', On: 'チャ、サ', Kun: 'ちゃ、さ' },
    { Id: '持', SinoVietnamese: 'TRÌ', On: 'ジ', Kun: 'も' },
    { Id: '願', SinoVietnamese: 'NGUYỆN', On: 'ガン', Kun: 'ねが' },
    { Id: '料', SinoVietnamese: 'LIÊU, LIỆU', On: 'リョウ', Kun: 'りょう' },
    { Id: '理', SinoVietnamese: 'LÍ', On: 'リ', Kun: 'ことわり' },
    { Id: '味', SinoVietnamese: 'VỊ', On: 'ミ', Kun: 'あじ' },
    { Id: '色', SinoVietnamese: 'SẮC', On: 'ショク、シキ', Kun: 'いろ' },
    { Id: '野', SinoVietnamese: 'DÃ', On: 'ヤ、ショ', Kun: 'の' },
    { Id: '菜', SinoVietnamese: 'THÁI', On: 'サイ', Kun: 'な' },
    { Id: '中', SinoVietnamese: 'TRUNG', On: 'チュウ', Kun: 'なか、うち、あた' },
    { Id: '入', SinoVietnamese: 'NHẬP', On: 'ニュウ、ジュ', Kun: 'はい、い' },

    { Id: '社', SinoVietnamese: 'XÃ', On: 'シャ', Kun: 'やしろ' },
    { Id: '支', SinoVietnamese: 'CHI', On: 'シ', Kun: 'ささ、つか、か' },
    { Id: '張', SinoVietnamese: 'TRƯƠNG, TRƯỚNG', On: 'チョウ', Kun: 'は、ば' },
    { Id: '発', SinoVietnamese: 'PHÁT', On: 'ハツ、ホツ', Kun: 'た、あば、おこ、つか、はな' },
    { Id: '港', SinoVietnamese: 'CẢNG', On: 'コウ', Kun: 'みなと' },
    { Id: '到', SinoVietnamese: 'ĐÁO', On: 'トウ', Kun: 'いた' },
    { Id: '着', SinoVietnamese: 'TRƯỚC', On: 'チャク、ジャク', Kun: 'き、つ' },
    { Id: '自', SinoVietnamese: 'TỰ', On: 'ジ、シ', Kun: 'みずか' },
    { Id: '車', SinoVietnamese: 'XA', On: 'シャ', Kun: 'くるま' },
    { Id: '電', SinoVietnamese: 'ĐIỆN', On: 'デン', Kun: 'でん' },
    { Id: '使', SinoVietnamese: 'SỨ', On: 'シ', Kun: 'つか、づか' },
    { Id: '借', SinoVietnamese: 'TÁ', On: 'シャク', Kun: 'か' },
    { Id: '送', SinoVietnamese: 'TỐNG', On: 'ソウ', Kun: 'おく' },

    { Id: '体', SinoVietnamese: 'THỂ', On: 'タイ、テイ', Kun: 'からだ、かたち' },
    { Id: '頭', SinoVietnamese: 'ĐẦU', On: 'トウ、ズ、ト', Kun: 'あたま、かしら、がしら、かぶり' },
    { Id: '目', SinoVietnamese: 'MỤC', On: 'モク、ボク', Kun: 'め、ま' },
    { Id: '耳', SinoVietnamese: 'NHĨ', On: 'ジ', Kun: 'みみ' },
    { Id: '上', SinoVietnamese: 'THƯỢNG', On: 'ジョウ、ショウ、シャン', Kun: 'うえ、うわ、かみ、あ、のぼ、よ' },
    { Id: '下', SinoVietnamese: 'HẠ', On: 'カ、ゲ', Kun: 'した、しも、もと、さ、くだ、お' },
    { Id: '手', SinoVietnamese: 'THỦ', On: 'シュ、ズ', Kun: 'て、た' },
    { Id: '足', SinoVietnamese: 'TÚC', On: 'ソク', Kun: 'あし、た' },
    { Id: '毎', SinoVietnamese: 'MỖI', On: 'マイ、バイ', Kun: 'つね' },
    { Id: '末', SinoVietnamese: 'MẠT', On: 'マツ、バツ', Kun: 'すえ' },
    { Id: '元', SinoVietnamese: 'NGUYÊN', On: 'ゲン、ガン', Kun: 'もと' },
    { Id: '起', SinoVietnamese: 'KHỞI', On: 'キ', Kun: 'お、おこ、た' },
    { Id: '歩', SinoVietnamese: 'BỘ', On: 'ホ、ブ、フ', Kun: 'ある、あゆ' },
    { Id: '走', SinoVietnamese: 'TẨU', On: 'ソウ', Kun: 'はし' },
    { Id: '泳', SinoVietnamese: 'VỊNH', On: 'エイ', Kun: 'およ' },

    { Id: '祝', SinoVietnamese: 'CHÚC', On: 'シュク、シュウ', Kun: 'いわ' },
    { Id: '誕', SinoVietnamese: 'ĐẢN', On: 'タン', Kun: 'たん' },
    { Id: '結', SinoVietnamese: 'KẾT', On: 'ケツ、ケチ', Kun: 'むす、ゆ' },
    { Id: '婚', SinoVietnamese: 'HÔN', On: 'コン', Kun: 'こん' },
    { Id: '絵', SinoVietnamese: 'HỘI', On: 'カイ、エ', Kun: 'かい、え' },
    { Id: '写', SinoVietnamese: 'TẢ', On: 'シャ、ジャ', Kun: 'うつ' },
    { Id: '真', SinoVietnamese: 'CHÂN', On: 'シン', Kun: 'ま、まこと' },
    { Id: '計', SinoVietnamese: 'KẾ', On: 'ケイ', Kun: 'はか' },
    { Id: '家', SinoVietnamese: 'GIA', On: 'カ、ケ', Kun: 'いえ、や、うち' },
    { Id: '思', SinoVietnamese: 'TƯ, TỨ', On: 'シ', Kun: 'おも、おぼ' },
    { Id: '去', SinoVietnamese: 'KHỨ', On: 'キョ、こ', Kun: 'さ' },

    { Id: '己', SinoVietnamese: 'KỶ', On: 'コ、キ', Kun: 'おのれ、つちのと、な' },
    { Id: '紹', SinoVietnamese: 'THIỆU', On: 'ショウ', Kun: 'しょう' },
    { Id: '介', SinoVietnamese: 'GIỚI', On: 'カイ', Kun: 'かい' },
    { Id: '名', SinoVietnamese: 'DANH', On: 'メイ、ミョウ', Kun: 'な' },
    { Id: '意', SinoVietnamese: 'Ý', On: 'イ', Kun: 'い' },
    { Id: '屋', SinoVietnamese: 'ỐC', On: 'オク', Kun: 'や' },
    { Id: '近', SinoVietnamese: 'CẬN', On: 'キン、コン', Kun: 'ちか' },
    { Id: '住', SinoVietnamese: 'TRÚ', On: 'ジュウ、チュウ', Kun: 'す' },
    { Id: '働', SinoVietnamese: 'ĐỘNG', On: 'ドウ、リュク', Kun: 'はたら' },
    { Id: '番', SinoVietnamese: 'PHIÊN', On: 'バン', Kun: 'つが' },

    { Id: '兄', SinoVietnamese: 'HUYNH', On: 'ケイ、キョウ', Kun: 'あに' },
    { Id: '姉', SinoVietnamese: 'TỈ', On: 'シ', Kun: 'あね' },
    { Id: '族', SinoVietnamese: 'TỘC', On: 'ゾク', Kun: 'ぞく' },
    { Id: '長', SinoVietnamese: 'TRƯỜNG', On: 'チョウ', Kun: 'なが' },
    { Id: '短', SinoVietnamese: 'ĐOẢN', On: 'タン', Kun: 'みじか' },
    { Id: '低', SinoVietnamese: 'ĐÊ', On: 'テイ', Kun: 'ひく' },
    { Id: '歌', SinoVietnamese: 'CA', On: 'カ', Kun: 'うた' },

    { Id: '客', SinoVietnamese: 'KHÁCH', On: 'キャク、カク', Kun: 'きゃく、かく' },
    { Id: '注', SinoVietnamese: 'CHÚ', On: 'チュウ', Kun: 'そそ、つ、さ' },
    { Id: '洋', SinoVietnamese: 'DƯƠNG', On: 'ヨウ', Kun: 'よう' },
    { Id: '和', SinoVietnamese: 'HÒA', On: 'ワ、オ、カ', Kun: 'わ、お、か' },
    { Id: '地', SinoVietnamese: 'ĐỊA', On: 'チ、ジ', Kun: 'ち、じ' },
    { Id: '方', SinoVietnamese: 'PHƯƠNG', On: 'ホウ', Kun: 'かた、がた' },
    { Id: '有', SinoVietnamese: 'HỮU', On: 'ユウ、ウ', Kun: 'あ' },
    { Id: '牛', SinoVietnamese: 'NGƯU', On: 'ギュウ', Kun: 'うし' },
    { Id: '冷', SinoVietnamese: 'LÃNH', On: 'レイ', Kun: 'つめ、ひ、さ' },

    { Id: '飯', SinoVietnamese: 'PHẠN', On: 'ハン', Kun: 'めし' },
    { Id: '塩', SinoVietnamese: 'DIÊM', On: 'エン', Kun: 'しお' },
    { Id: '全', SinoVietnamese: 'TOÀN', On: 'ゼン', Kun: 'まった、すべ' },
    { Id: '部', SinoVietnamese: 'BỘ', On: 'ブ', Kun: 'べ' },
    { Id: '熱', SinoVietnamese: 'NHIỆT', On: 'ネツ', Kun: 'あつ' },
    { Id: '苦', SinoVietnamese: 'KHỔ', On: 'ク', Kun: 'くる、にが' },

    { Id: '森', SinoVietnamese: 'SÂM', On: 'シン', Kun: 'もり' },
    { Id: '島', SinoVietnamese: 'ĐẢO', On: 'トウ', Kun: 'しま' },
    { Id: '然', SinoVietnamese: 'NHIÊN', On: 'ゼン、ネン', Kun: 'ぜん、ねん' },
    { Id: '船', SinoVietnamese: 'THUYỀN', On: 'セン', Kun: 'ふね' },
    { Id: '暑', SinoVietnamese: 'THỬ', On: 'ショ', Kun: 'あつ' },
    { Id: '帰', SinoVietnamese: 'QUY', On: 'キ', Kun: 'かえ' },
    { Id: '予', SinoVietnamese: 'DỰ', On: 'ヨ、シャ', Kun: 'よ、しゃ' },
    { Id: '約', SinoVietnamese: 'ƯỚC', On: 'ヤク', Kun: 'やく' },
    { Id: '運', SinoVietnamese: 'VẬN', On: 'ウン', Kun: 'はこ' },
    { Id: '転', SinoVietnamese: 'CHUYỂN', On: 'テン', Kun: 'ころ' },

    { Id: '観', SinoVietnamese: 'QUAN', On: 'カン', Kun: 'み' },
    { Id: '光', SinoVietnamese: 'QUANG', On: 'コウ', Kun: 'ひか、ひかり' },
    { Id: '性', SinoVietnamese: 'TÍNH', On: 'セイ、ヒョウ', Kun: 'せい、ひょう' },
    { Id: '動', SinoVietnamese: 'ĐỘNG', On: 'ドウ', Kun: 'うご' },
    { Id: '無', SinoVietnamese: 'VÔ', On: 'ム、ブ', Kun: 'な' },
    { Id: '明', SinoVietnamese: 'MINH', On: 'メイ、ミョウ、ミン', Kun: 'あか' },
    { Id: '便', SinoVietnamese: 'TIỆN', On: 'ベン、ビン', Kun: 'たよ' },
    { Id: '利', SinoVietnamese: 'LỢI', On: 'リ', Kun: 'き' },

    { Id: '受', SinoVietnamese: 'THỤ', On: 'ジュ', Kun: 'う' },
    { Id: '付', SinoVietnamese: 'PHÓ', On: 'フ', Kun: 'つ' },
    { Id: '問', SinoVietnamese: 'VẤN', On: 'モン', Kun: 'とう、と' },
    { Id: '題', SinoVietnamese: 'ĐỀ', On: 'ダイ', Kun: 'だい' },
    { Id: '同', SinoVietnamese: 'ĐỒNG', On: 'ドウ', Kun: 'おな' },
    { Id: '集', SinoVietnamese: 'TẬP', On: 'シュウ', Kun: 'あつ' },
    { Id: '始', SinoVietnamese: 'THỦY', On: 'シ', Kun: 'はじ' },
    { Id: '終', SinoVietnamese: 'CHUNG', On: 'シュウ', Kun: 'お' },
    { Id: '教', SinoVietnamese: 'GIÁO', On: 'キョウ', Kun: 'おし、おそ' },

    { Id: '祭', SinoVietnamese: 'TẾ, SÁI', On: 'サイ', Kun: 'まつ' },
    { Id: '参', SinoVietnamese: 'THAM', On: 'サン、シン', Kun: 'まい' },
    { Id: '加', SinoVietnamese: 'GIA', On: 'カ', Kun: 'くわ' },
    { Id: '者', SinoVietnamese: 'GIẢ', On: 'シャ', Kun: 'もの' },
    { Id: '急', SinoVietnamese: 'CẤP', On: 'キュウ', Kun: 'いそ' },
    { Id: '決', SinoVietnamese: 'QUYẾT', On: 'ケツ', Kun: 'き' },
    { Id: '知', SinoVietnamese: 'TRI, TRÍ', On: 'チ', Kun: 'し、しら' },

    { Id: '正', SinoVietnamese: 'CHÍNH', On: 'セイ、ショウ', Kun: 'ただ' },
    { Id: '親', SinoVietnamese: 'THÂN', On: 'シン', Kun: 'おや、した' },
    { Id: '忙', SinoVietnamese: 'MANG', On: 'ボウ、モウ', Kun: 'いそが' },
    { Id: '特', SinoVietnamese: 'ĐẶC', On: 'トク', Kun: 'とく' },
    { Id: '別', SinoVietnamese: 'BIỆT', On: 'ベツ', Kun: 'わ、わか' },
    { Id: '喜', SinoVietnamese: 'HỶ', On: 'キ', Kun: 'よろこ' },

    { Id: '幸', SinoVietnamese: 'HẠNH', On: 'コウ', Kun: 'しあわ' },
    { Id: '成', SinoVietnamese: 'THÀNH', On: 'セイ、ジョウ', Kun: 'な' },
    { Id: '合', SinoVietnamese: 'HỢP', On: 'ゴウ、カツ、ガツ', Kun: 'あ' },
    { Id: '試', SinoVietnamese: 'THÍ', On: 'シ', Kun: 'こころ、ため' },
    { Id: '験', SinoVietnamese: 'NGHIỆM', On: 'ケン、ゲン', Kun: 'けん、げん' },
    { Id: '式', SinoVietnamese: 'THỨC', On: 'シキ', Kun: 'しき' },
    { Id: '市', SinoVietnamese: 'THỊ', On: 'シ', Kun: 'いち' },

    { Id: '商', SinoVietnamese: 'THƯƠNG', On: 'ショウ', Kun: 'あきな' },
    { Id: '品', SinoVietnamese: 'PHẨM', On: 'ヒン、ホン', Kun: 'しな' },
    { Id: '製', SinoVietnamese: 'CHẾ', On: 'セイ', Kun: 'せい' },
    { Id: '機', SinoVietnamese: 'KI, CƠ', On: 'キ', Kun: 'はた' },
    { Id: '員', SinoVietnamese: 'VIÊN', On: 'イン', Kun: 'いん' },
    { Id: '調', SinoVietnamese: 'ĐIỀU', On: 'チョウ', Kun: 'しら' },
    { Id: '悪', SinoVietnamese: 'ÁC', On: 'アク、オ', Kun: 'わる' },
    { Id: '考', SinoVietnamese: 'KHẢO', On: 'コウ', Kun: 'かんが' },

    { Id: '能', SinoVietnamese: 'NĂNG', On: 'ノウ', Kun: 'よ' },
    { Id: '省', SinoVietnamese: 'TỈNH', On: 'セイ、ショウ', Kun: 'かえり' },
    { Id: '重', SinoVietnamese: 'TRỌNG', On: 'ジュウ、チョウ', Kun: 'おも、かさ' },
    { Id: '軽', SinoVietnamese: 'KHINH', On: 'ケイ', Kun: 'かる' },
    { Id: '静', SinoVietnamese: 'TĨNH', On: 'セイ、ジョウ', Kun: 'しず' },
    { Id: '早', SinoVietnamese: 'TẢO', On: 'ソウ', Kun: 'はや' },
    { Id: '洗', SinoVietnamese: 'TẨY', On: 'セン', Kun: 'あら' },
    { Id: '満', SinoVietnamese: 'MÃN', On: 'マン、バン', Kun: 'み' },

    { Id: '都', SinoVietnamese: 'ĐÔ', On: 'ト、ツ', Kun: 'と、つ' },
    { Id: '神', SinoVietnamese: 'THẦN', On: 'シン', Kun: 'かみ' },
    { Id: '寺', SinoVietnamese: 'TỰ', On: 'ジ', Kun: 'てら' },
    { Id: '仏', SinoVietnamese: 'PHẬT', On: 'ブツ、フツ', Kun: 'ほとけ' },
    { Id: '歴', SinoVietnamese: 'LỊCH', On: 'レキ', Kun: 'れき' },
    { Id: '史', SinoVietnamese: 'SỬ', On: 'シ', Kun: 'し' },
    { Id: '世', SinoVietnamese: 'THẾ', On: 'セイ、セ、ソウ', Kun: 'よ' },
    { Id: '界', SinoVietnamese: 'GIỚI', On: 'カイ', Kun: 'かい' },
    { Id: '心', SinoVietnamese: 'TÂM', On: 'シン', Kun: 'こころ、ごころ' },
    { Id: '紀', SinoVietnamese: 'KỈ', On: 'キ', Kun: 'き' },
    { Id: '的', SinoVietnamese: 'ĐÍCH', On: 'テキ', Kun: 'まと' },

    { Id: '禁', SinoVietnamese: 'CẤM', On: 'キン', Kun: 'きん' },
    { Id: '説', SinoVietnamese: 'THUYẾT', On: 'セイ、ゼイ', Kun: 'と' },
    { Id: '具', SinoVietnamese: 'CỤ', On: 'グ', Kun: 'そな' },
    { Id: '博', SinoVietnamese: 'BÁC', On: 'ハク、バク', Kun: 'はく、ばく' },
    { Id: '館', SinoVietnamese: 'QUÁN', On: 'カン', Kun: 'やかた、たて' },
    { Id: '必', SinoVietnamese: 'TẤT', On: 'ヒツ', Kun: 'かなら' },
    { Id: '要', SinoVietnamese: 'YẾU', On: 'ヨウ', Kun: 'い' },
    { Id: '階', SinoVietnamese: 'GIAI', On: 'カイ', Kun: 'きざはし' },

    { Id: '油', SinoVietnamese: 'DU', On: 'アブラ', Kun: 'ゆ、ゆう' },
    { Id: '紙', SinoVietnamese: 'CHỈ', On: 'シ', Kun: 'かみ' },
    { Id: '温', SinoVietnamese: 'ÔN, UẨN', On: 'オン', Kun: 'あたた' },
    { Id: '度', SinoVietnamese: 'ĐỘ', On: 'ド、ト、タク', Kun: 'たび' },
    { Id: '活', SinoVietnamese: 'HOẠT', On: 'カツ', Kun: 'い' },
    { Id: '議', SinoVietnamese: 'NGHỊ', On: 'ギ', Kun: 'ぎ' },
    { Id: '室', SinoVietnamese: 'THẤT', On: 'シツ', Kun: 'むろ' },
    { Id: '寒', SinoVietnamese: 'HÀN', On: 'カン', Kun: 'さむ' },
    { Id: '点', SinoVietnamese: 'ĐIỂM', On: 'テン', Kun: 'つ' },

    { Id: '服', SinoVietnamese: 'PHỤC', On: 'フク', Kun: 'ふく' },
    { Id: '売', SinoVietnamese: 'MẠI', On: 'バイ', Kun: 'う' },
    { Id: '貸', SinoVietnamese: 'THẢI, THẮC', On: 'タイ', Kun: 'か' },
    { Id: '返', SinoVietnamese: 'PHẢN', On: 'ヘン', Kun: 'かえ' },
    { Id: '変', SinoVietnamese: 'BIẾN', On: 'ヘン', Kun: 'か' },
    { Id: '用', SinoVietnamese: 'DỤNG', On: 'ヨウ', Kun: 'もち' },

    { Id: '選', SinoVietnamese: 'TUYỂN', On: 'セン', Kun: 'えら' },
    { Id: '画', SinoVietnamese: 'HỌA, HOẠCH', On: 'ガ、カク、エ、カイ', Kun: 'えが、はか' },
    { Id: '卒', SinoVietnamese: 'TỐT', On: 'ソツ、シュツ', Kun: 'そっ、お、…' },
    { Id: '業', SinoVietnamese: 'NGHIỆP', On: 'ギョウ、ゴウ', Kun: 'わざ' },
    { Id: '病', SinoVietnamese: 'BỆNH', On: 'ビョウ、ヘイ', Kun: 'や' },
    { Id: '若', SinoVietnamese: 'NHƯỢC', On: 'ニャク、ジャク、ニャ', Kun: 'わか' },

    { Id: '映', SinoVietnamese: 'ÁNH', On: 'エイ', Kun: 'うつ' },
    { Id: '夫', SinoVietnamese: 'PHU', On: 'フウ、フ、ブ', Kun: 'おっと' },
    { Id: '妻', SinoVietnamese: 'THÊ', On: 'サイ', Kun: 'つま' },
    { Id: '両', SinoVietnamese: 'LƯỠNG', On: 'リョウ', Kun: 'てる、ふたつ' },
    { Id: '不', SinoVietnamese: 'BẤT', On: 'フ、ブ', Kun: 'ふ、ぶ' },
    { Id: '寝', SinoVietnamese: 'TẨM', On: 'シン', Kun: 'ね' },

    // { Id: 'NoKanji', SinoVietnamese: 'NoKanji', On: 'NoKanji', Kun: 'NoKanji' },
    // { Id: 'NoKanji', SinoVietnamese: 'NoKanji', On: 'NoKanji', Kun: 'NoKanji' },
    // { Id: 'NoKanji', SinoVietnamese: 'NoKanji', On: 'NoKanji', Kun: 'NoKanji' },
    // { Id: 'NoKanji', SinoVietnamese: 'NoKanji', On: 'NoKanji', Kun: 'NoKanji' },
];

export const KanjiExample = [
    // { Word: '月曜日', Hiragana: 'げつようび', Meaning: 'Thứ 2' },
    // { Word: '火曜日', Hiragana: 'かようび', Meaning: 'Thứ 3' },
    // { Word: '水曜日', Hiragana: 'すいようび', Meaning: 'Thứ 4' },
    // { Word: '木曜日', Hiragana: 'もくようび', Meaning: 'Thứ 5' },
    // { Word: '金曜日', Hiragana: 'きんようび', Meaning: 'Thứ 6' },
    // { Word: '土曜日', Hiragana: 'どようび', Meaning: 'Thứ 7' },
    // { Word: '日曜日', Hiragana: 'にちようび', Meaning: 'Chủ Nhật' },



    { Word: '魚', Hiragana: 'さかな', Meaning: 'Cá' },
    { Word: '人魚', Hiragana: 'にんぎょ', Meaning: 'Người cá' },
    { Word: '金魚', Hiragana: 'きんぎょ', Meaning: 'Cá vàng' },

    { Word: '肉', Hiragana: 'にく', Meaning: 'Thịt' },
    { Word: '牛肉', Hiragana: 'ぎゅうにく', Meaning: 'Thịt bò' },
    { Word: '焼き肉', Hiragana: 'やきにく', Meaning: 'Thịt nướng' },

    { Word: '卵', Hiragana: 'たまご', Meaning: 'Trứng' },
    { Word: '卵焼き', Hiragana: 'たまごやき', Meaning: 'Trứng rán' },



    { Word: '月', Hiragana: 'つき', Meaning: 'Mặt Trăng' },
    { Word: '月曜日', Hiragana: 'げつようび', Meaning: 'Thứ 2' },
    { Word: '五月', Hiragana: 'ごがつ', Meaning: 'Tháng 5' },
    { Word: 'お正月', Hiragana: 'おしょうがつ', Meaning: 'Tết dương lịch' },

    { Word: '火', Hiragana: 'ひ', Meaning: 'Lửa' },
    { Word: '火曜日', Hiragana: 'かようび', Meaning: 'Thứ 3' },
    { Word: '火事', Hiragana: 'かじ', Meaning: 'Hỏa hoạn' },

    { Word: '水', Hiragana: 'みず', Meaning: 'Nước' },
    { Word: '水曜日', Hiragana: 'すいようび', Meaning: 'Thứ 4' },
    { Word: '香水', Hiragana: 'こうすい', Meaning: 'Nước hoa' },

    { Word: '木', Hiragana: 'き', Meaning: 'Cây' },
    { Word: '木曜日', Hiragana: 'もくようび', Meaning: 'Thứ 5' },

    { Word: '金', Hiragana: 'きん', Meaning: 'Tiền, vàng' },
    { Word: '金曜日', Hiragana: 'きんようび', Meaning: 'Thứ 6' },
    { Word: 'お金', Hiragana: 'おかね', Meaning: 'Tiền' },
    { Word: 'お金持ち', Hiragana: 'おかねもち', Meaning: 'Người giàu' },

    { Word: '土', Hiragana: 'つち', Meaning: 'Đất' },
    { Word: '土曜日', Hiragana: 'どようび', Meaning: 'Thứ 7' },

    { Word: '日', Hiragana: 'ひ', Meaning: 'Mặt Trời, ngày' },
    { Word: '日曜日', Hiragana: 'にちようび', Meaning: 'Chủ Nhật' },
    { Word: '土日', Hiragana: 'どにち', Meaning: 'Cuối tuần' },



    { Word: '大きい', Hiragana: 'おおきい', Meaning: 'To, lớn' },
    { Word: '大学', Hiragana: 'だいがく', Meaning: 'Đại học' },
    { Word: '大丈夫', Hiragana: 'だいじょうぶ', Meaning: 'Không sao, ổn' },
    { Word: '大事', Hiragana: 'だいじ', Meaning: 'Việc quan trọng' },
    { Word: '大切', Hiragana: 'たいせつ', Meaning: 'Quan trọng' },
    { Word: '大人', Hiragana: 'おとな', Meaning: 'Người lớn' },

    { Word: '小さい', Hiragana: 'ちいさい', Meaning: 'Bé, nhỏ' },
    { Word: '小麦', Hiragana: 'こむぎ', Meaning: 'Lúa mì' },
    { Word: '小猫', Hiragana: 'こねこ', Meaning: 'Con mèo con' },
    { Word: '小川', Hiragana: 'おがわ', Meaning: 'Sông nhỏ' },
    { Word: '小学生', Hiragana: 'しょうがくせい', Meaning: 'Học sinh tiểu học' },

    { Word: '新しい', Hiragana: 'あたらしい', Meaning: 'Mới' },
    { Word: '新たな', Hiragana: 'あらたな', Meaning: 'Mới' },
    { Word: '新潟県', Hiragana: 'にいがたけん', Meaning: 'Tỉnh Niigata' },
    { Word: '新幹線', Hiragana: 'しんかんせん', Meaning: 'Tàu siêu tốc' },

    { Word: '古い', Hiragana: 'ふるい', Meaning: 'Cũ' },
    { Word: '中古', Hiragana: 'ちゅうこ', Meaning: 'Trung cổ' },
    { Word: '古代', Hiragana: 'こだい', Meaning: 'Cổ đại' },
    { Word: '考古学', Hiragana: 'こうこがく', Meaning: 'Khảo cổ học' },

    { Word: '時', Hiragana: 'とき', Meaning: 'Khi, lúc' },
    { Word: '時々', Hiragana: 'ときどき', Meaning: 'Thỉnh thoảng' },
    { Word: '一時', Hiragana: 'いちじ', Meaning: '1 giờ' },
    { Word: '時間', Hiragana: 'じかん', Meaning: 'Thời gian' },
    { Word: '時計', Hiragana: 'とけい', Meaning: 'Đồng hồ' },

    { Word: '分かります', Hiragana: 'わかります', Meaning: 'Hiểu, biết' },
    { Word: '分けます', Hiragana: 'わけます', Meaning: 'Chia, phân chia' },
    { Word: '五分', Hiragana: 'ごふん', Meaning: '5 phút' },
    { Word: '十分', Hiragana: 'じっぷん', Meaning: '10 phút' },
    { Word: '十分', Hiragana: 'じゅっぷん', Meaning: '10 phút' },
    { Word: '十分', Hiragana: 'じゅうぶん', Meaning: 'Đủ rồi' },
    { Word: '自分', Hiragana: 'じぶん', Meaning: 'Tự mình' },

    { Word: '一月半ば', Hiragana: 'いちがつなかば', Meaning: 'Giữa tháng 1' },
    { Word: '四時半', Hiragana: 'よじはん', Meaning: '4 giờ rưỡi' },
    { Word: '半分', Hiragana: 'はんぶん', Meaning: 'Một nửa' },



    { Word: '言う', Hiragana: 'いう', Meaning: 'Nói' },
    { Word: '言葉', Hiragana: 'ことば', Meaning: 'Từ ngữ' },
    { Word: '方言', Hiragana: 'ほうげん', Meaning: 'Tiếng địa phương' },
    { Word: '言語', Hiragana: 'げんご', Meaning: 'Ngôn ngữ' },
    { Word: '伝言', Hiragana: 'でんごん', Meaning: 'Lời nhắn' },

    { Word: '話す', Hiragana: 'はなす', Meaning: 'Nói chuyện' },
    { Word: '話', Hiragana: 'はなし', Meaning: 'Câu chuyện' },
    { Word: '電話', Hiragana: 'でんわ', Meaning: 'Điện thoại' },
    { Word: '会話', Hiragana: 'かいわ', Meaning: 'Hội thoại' },

    { Word: '読む', Hiragana: 'よむ', Meaning: 'Đọc' },
    { Word: '読み物', Hiragana: 'よみもの', Meaning: 'Tài liệu đọc' },
    { Word: '読書', Hiragana: 'どくしょ', Meaning: 'Đọc sách' },
    { Word: '読者', Hiragana: 'どくしゃ', Meaning: 'Người đọc' },
    { Word: '句読点', Hiragana: 'くとうてん', Meaning: 'Dấu chấm câu' },

    { Word: '見る', Hiragana: 'みる', Meaning: 'Xem, nhìn, trông' },
    { Word: '見せる', Hiragana: 'みせる', Meaning: 'Cho xem' },
    { Word: '意見', Hiragana: 'いけん', Meaning: 'Ý kiến' },
    { Word: '見学', Hiragana: 'けんがく', Meaning: 'Kiến học' },

    { Word: '聞く', Hiragana: 'きく', Meaning: 'Nghe' },
    { Word: '新聞', Hiragana: 'しんぶん', Meaning: 'Báo' },
    { Word: '聞き取る', Hiragana: 'ききとる', Meaning: 'Nắm bắt, nghe hiểu' },
    { Word: '聞こえる', Hiragana: 'きこえる', Meaning: 'Có thể nghe thấy' },

    { Word: '書く', Hiragana: 'かく', Meaning: 'Viết' },
    { Word: '辞書', Hiragana: 'じしょ', Meaning: 'Từ điển' },
    { Word: '教科書', Hiragana: 'きょうかしょ', Meaning: 'Sách giáo khoa' },
    { Word: '図書館', Hiragana: 'としょかん', Meaning: 'Thư viện' },



    { Word: '一', Hiragana: 'いち', Meaning: 'Số 1' },
    { Word: '一日', Hiragana: 'ついたち', Meaning: 'Mùng 1' },
    { Word: '一つ', Hiragana: 'ひとつ', Meaning: '1 cái' },
    { Word: '一人', Hiragana: 'ひとり', Meaning: '1 người' },
    { Word: '一日中', Hiragana: 'いちにちじゅう', Meaning: 'Trong 1 ngày' },

    { Word: '二', Hiragana: 'に', Meaning: 'Số 2' },
    { Word: '二日', Hiragana: 'ふつか', Meaning: 'Mùng 2' },
    { Word: '二つ', Hiragana: 'ふたつ', Meaning: '2 cái' },
    { Word: '二人', Hiragana: 'ふたり', Meaning: '2 người' },

    { Word: '三', Hiragana: 'さん', Meaning: 'Số 3' },
    { Word: '三日', Hiragana: 'みっか', Meaning: 'Mùng 3' },
    { Word: '三つ', Hiragana: 'みっつ', Meaning: '3 cái' },
    { Word: '三人', Hiragana: 'さんにん', Meaning: '3 người' },

    { Word: '四', Hiragana: 'よん・し', Meaning: 'Số 4' },
    { Word: '四日', Hiragana: 'よっか', Meaning: 'Mùng 4' },
    { Word: '四つ', Hiragana: 'よっつ', Meaning: '4 cái' },
    { Word: '四人', Hiragana: 'よにん', Meaning: '4 người' },
    { Word: '四季', Hiragana: 'しき', Meaning: '4 mùa' },

    { Word: '五', Hiragana: 'ご', Meaning: 'Số 5' },
    { Word: '五日', Hiragana: 'いつか', Meaning: 'Mùng 5' },
    { Word: '五つ', Hiragana: 'いつつ', Meaning: '5 cái' },
    { Word: '五人', Hiragana: 'ごにん', Meaning: '5 người' },

    { Word: '六', Hiragana: 'ろく', Meaning: 'Số 6' },
    { Word: '六日', Hiragana: 'むいか', Meaning: 'Mùng 6' },
    { Word: '六つ', Hiragana: 'むっつ', Meaning: '6 cái' },
    { Word: '六人', Hiragana: 'ろくにん', Meaning: '6 người' },

    { Word: '七', Hiragana: 'なな・しち', Meaning: 'Số 7' },
    { Word: '七日', Hiragana: 'なのか', Meaning: 'Mùng 7' },
    { Word: '七つ', Hiragana: 'ななつ', Meaning: '7 cái' },
    { Word: '七人', Hiragana: 'ななにん', Meaning: '7 người' },

    { Word: '八', Hiragana: 'はち', Meaning: 'Số 8' },
    { Word: '八日', Hiragana: 'ようか', Meaning: 'Mùng 8' },
    { Word: '八つ', Hiragana: 'やっつ', Meaning: '8 cái' },
    { Word: '八人', Hiragana: 'はちにん', Meaning: '8 người' },

    { Word: '九', Hiragana: 'きゅう・く', Meaning: 'Số 9' },
    { Word: '九日', Hiragana: 'ここのか', Meaning: 'Mùng 9' },
    { Word: '九つ', Hiragana: 'ここのつ', Meaning: '9 cái' },
    { Word: '九人', Hiragana: 'きゅうにん', Meaning: '9 người' },

    { Word: '十', Hiragana: 'じゅう', Meaning: 'Số 10' },
    { Word: '十日', Hiragana: 'とおか', Meaning: 'Mùng 10' },
    { Word: '十つ', Hiragana: 'じゅうつ', Meaning: '10 cái' },////////////////////////////////////////////////////////////////////
    { Word: '十人', Hiragana: 'じゅうにん', Meaning: '10 người' },////////////////////////////////////////////////////////////////////

    { Word: '一年', Hiragana: 'いちねん', Meaning: '1 năm' },
    { Word: '半年', Hiragana: 'はんとし', Meaning: 'Nửa năm' },



    { Word: '東', Hiragana: 'ひがし', Meaning: 'Phía Đông' },
    { Word: '東口', Hiragana: 'ひがしぐち', Meaning: 'Cửa Đông' },
    { Word: '中東', Hiragana: 'ちゅうとう', Meaning: 'Trung Đông' },
    { Word: '東京', Hiragana: 'とうきょう', Meaning: 'Tokyo' },
    { Word: '東洋', Hiragana: 'とうよう', Meaning: 'Đông Dương' },

    { Word: '西', Hiragana: 'にし', Meaning: 'Phía Tây' },
    { Word: '西口', Hiragana: 'にしぐち', Meaning: 'Cửa Tây' },
    { Word: '北西', Hiragana: 'ほくせい', Meaning: 'Tây Bắc' },
    { Word: '大西洋', Hiragana: 'たいせいよう', Meaning: 'Đại Tây Dương' },
    { Word: '東西', Hiragana: 'とうざい', Meaning: 'Đông Tây' },
    { Word: '関西', Hiragana: 'かんさい', Meaning: 'Vùng Kansai' },

    { Word: '南', Hiragana: 'みなみ', Meaning: 'Phía Nam' },
    { Word: '南口', Hiragana: 'みなみぐち', Meaning: 'Cửa Nam' },
    { Word: '東南アジア', Hiragana: 'とうなんアジア', Meaning: 'Đông Nam Á' },
    { Word: '南西', Hiragana: 'なんせい', Meaning: 'Tây Nam' },
    { Word: '南極', Hiragana: 'なんきょく', Meaning: 'Nam Cực' },

    { Word: '北', Hiragana: 'きた', Meaning: 'Phía Bắc' },
    { Word: '北口', Hiragana: 'きたぐち', Meaning: 'Cửa Bắc' },
    { Word: '北東', Hiragana: 'ほくとう', Meaning: 'Đông Bắc' },
    { Word: '北海道', Hiragana: 'ほっかいどう', Meaning: 'Hokkaido' },
    { Word: '南北', Hiragana: 'なんぼく', Meaning: 'Nam Bắc' },

    { Word: '口', Hiragana: 'くち', Meaning: 'Miệng' },
    { Word: '入り口', Hiragana: 'いりぐち', Meaning: 'Cửa vào' },
    { Word: '出口', Hiragana: 'でぐち', Meaning: 'Cửa ra' },
    { Word: '人口', Hiragana: 'じんこう', Meaning: 'Dân số' },
    { Word: '口調', Hiragana: 'くちょう', Meaning: 'Giọng điệu' },



    { Word: '買います', Hiragana: 'かいます', Meaning: 'Mua' },
    { Word: '買い物', Hiragana: 'かいもの', Meaning: 'Sự mua sắm' },
    { Word: '売買', Hiragana: 'ばいばい', Meaning: 'Sự mua bán' },

    { Word: '百', Hiragana: 'ひゃく', Meaning: 'Một trăm' },
    { Word: '三百', Hiragana: 'さんびゃく', Meaning: 'Ba trăm' },
    { Word: '百貨店', Hiragana: 'ひゃっかてん', Meaning: 'Cửa hàng bách hóa' },

    { Word: '千', Hiragana: 'せん', Meaning: 'Một ngàn' },
    { Word: '千円', Hiragana: 'せんえん', Meaning: 'Một ngàn yên' },
    { Word: '千人', Hiragana: 'せんにん', Meaning: 'Một ngàn người' },

    { Word: '一万', Hiragana: 'いちまん', Meaning: 'Một vạn' },
    { Word: '一万円', Hiragana: 'いちまんえん', Meaning: 'Một vạn yên' },
    { Word: '万事', Hiragana: 'ばんじ', Meaning: 'Vạn sự' },

    { Word: '円', Hiragana: 'えん', Meaning: 'Yên' },
    { Word: '百円', Hiragana: 'ひゃくえん', Meaning: 'Một trăm yên' },
    { Word: '一千万円', Hiragana: 'いっせんまんえん', Meaning: 'Một ngàn vạn yên' },

    { Word: '人物', Hiragana: 'じんぶつ', Meaning: 'Nhân vật' },
    { Word: '見物', Hiragana: 'けんぶつ', Meaning: 'Ngắm cảnh' },



    { Word: '行く', Hiragana: 'いく', Meaning: 'Đi' },
    { Word: '行く', Hiragana: 'ゆく', Meaning: 'Đi' },
    { Word: '行う', Hiragana: 'おこなう', Meaning: 'Tiến hành' },
    { Word: '銀行', Hiragana: 'ぎんこう', Meaning: 'Ngân hàng' },
    { Word: '旅行', Hiragana: 'りょこう', Meaning: 'Du lịch' },
    { Word: '行事', Hiragana: 'ぎょうじ', Meaning: 'Sự kiện' },

    { Word: '来る', Hiragana: 'くる', Meaning: 'Đến' },
    { Word: '来ます', Hiragana: 'きます', Meaning: 'Đến (Lịch sự)' },
    { Word: '来ない', Hiragana: 'こない', Meaning: 'Không đến' },
    { Word: '来年', Hiragana: 'らいねん', Meaning: 'Năm sau' },
    { Word: '来日', Hiragana: 'らいにち', Meaning: 'Đến Nhật Bản' },
    { Word: '来る', Hiragana: 'きたる', Meaning: 'Học kì tới' },

    { Word: '会う', Hiragana: 'あう', Meaning: 'Gặp' },
    { Word: '会議', Hiragana: 'かいぎ', Meaning: 'Hội nghị' },
    { Word: '会釈', Hiragana: 'えしゃく', Meaning: 'Gật đầu' },

    { Word: '休む', Hiragana: 'やすむ', Meaning: 'Nghỉ ngơi' },
    { Word: '休み', Hiragana: 'やすみ', Meaning: 'Ngày nghỉ' },
    { Word: '昼休み', Hiragana: 'ひるやすみ', Meaning: 'Nghỉ trưa' },
    { Word: '夏休み', Hiragana: 'なつやすみ', Meaning: 'Nghỉ Hè' },
    { Word: '休日', Hiragana: 'きゅうじつ', Meaning: 'Ngày nghỉ (Trang trọng)' },

    { Word: '本', Hiragana: 'ほん', Meaning: 'Sách' },
    { Word: '日本', Hiragana: 'にほん', Meaning: 'Nhật Bản' },

    { Word: '京都', Hiragana: 'きょうと', Meaning: 'Kyoto' },
    { Word: '京子', Hiragana: 'きょうこ', Meaning: 'Kyoko (Tên nữ)' },
    { Word: '上京する', Hiragana: 'じょうきょうする', Meaning: 'Đi lên Tokyo' },



    { Word: '私', Hiragana: 'わたし', Meaning: 'Tôi' },
    { Word: '私たち', Hiragana: 'わたしたち', Meaning: 'Chúng ta' },
    { Word: '私立大学', Hiragana: 'しりつだいがく', Meaning: 'Đại học tư lập' },

    { Word: '父', Hiragana: 'ちち', Meaning: 'Bố' },
    { Word: '祖父', Hiragana: 'そふ', Meaning: 'Ông' },
    { Word: 'お父さん', Hiragana: 'おとうさん', Meaning: 'Bố người khác' },

    { Word: '母', Hiragana: 'はは', Meaning: 'Mẹ' },
    { Word: '母国語', Hiragana: 'ぼこくご', Meaning: 'Tiếng mẹ đẻ' },
    { Word: 'お母さん', Hiragana: 'おかあさん', Meaning: 'Mẹ người khác' },

    { Word: '子ども', Hiragana: 'こども', Meaning: 'Trẻ em' },
    { Word: '女の子', Hiragana: 'おんなのこ', Meaning: 'Bé gái' },
    { Word: '男の子', Hiragana: 'おとこのこ', Meaning: 'Bé trai' },

    { Word: '男の人', Hiragana: 'おとこのひと', Meaning: 'Người đàn ông' },
    { Word: '男子', Hiragana: 'だんし', Meaning: 'Người con trai' },

    { Word: '女の人', Hiragana: 'おんなのひと', Meaning: 'Người phụ nữ' },
    { Word: '女子', Hiragana: 'じょし', Meaning: 'Người con gái' },

    { Word: '人', Hiragana: 'ひと', Meaning: 'Người' },
    { Word: 'ベトナム人', Hiragana: 'ベトナムじん', Meaning: 'Người Việt Nam' },

    { Word: '何', Hiragana: 'なに', Meaning: 'Cái gì' },
    { Word: '何人', Hiragana: 'なんにん', Meaning: 'Mấy người' },
    { Word: '何人', Hiragana: 'なにじん', Meaning: 'Người nước nào' },



    { Word: '好き', Hiragana: 'すき', Meaning: 'Thích' },

    { Word: '日本語', Hiragana: 'にほんご', Meaning: 'Tiếng Nhật' },
    { Word: 'ベトナム語', Hiragana: 'ベトナムご', Meaning: 'Tiếng Việt' },
    { Word: '英語', Hiragana: 'えいご', Meaning: 'Tiếng Anh' },

    { Word: '外', Hiragana: 'そと', Meaning: 'Bên ngoài' },
    { Word: '外国人', Hiragana: 'がいこくじん', Meaning: 'Người nước ngoài' },
    { Word: '外国語', Hiragana: 'がいこくご', Meaning: 'Ngôn ngữ nước ngoài' },

    { Word: '国', Hiragana: 'くに', Meaning: 'Đất nước' },
    { Word: '国家', Hiragana: 'こっか', Meaning: 'Quốc gia' },
    { Word: '国語', Hiragana: 'こくご', Meaning: 'Quốc ngữ' },



    { Word: '春', Hiragana: 'はる', Meaning: 'Mùa Xuân' },
    { Word: '春巻き', Hiragana: 'はるまき', Meaning: 'Gỏi cuốn' },
    { Word: '夏', Hiragana: 'なつ', Meaning: 'Mùa Hạ' },
    { Word: '秋', Hiragana: 'あき', Meaning: 'Mùa Thu' },
    { Word: '中秋', Hiragana: 'ちゅうしゅう', Meaning: 'Tết Trung Thu' },
    { Word: '冬', Hiragana: 'ふゆ', Meaning: 'Mùa Đông' },
    { Word: '冬祭り', Hiragana: 'ふゆまつり', Meaning: 'Lễ hội Mùa Đông' },

    { Word: '今', Hiragana: 'いま', Meaning: 'Bây giờ' },
    { Word: '今朝', Hiragana: 'けさ', Meaning: 'Sáng nay' },
    { Word: '今日', Hiragana: 'きょう', Meaning: 'Hôm nay' },
    { Word: '今年', Hiragana: 'ことし', Meaning: 'Năm nay' },

    { Word: '花', Hiragana: 'はな', Meaning: 'Hoa' },
    { Word: '花見', Hiragana: 'はなみ', Meaning: 'Sự ngắm hoa' },
    { Word: '花火', Hiragana: 'はなび', Meaning: 'Pháo hoa' },

    { Word: '海', Hiragana: 'うみ', Meaning: 'Biển' },
    { Word: '海産', Hiragana: 'かいさん', Meaning: 'Hải sản' },

    { Word: '山', Hiragana: 'やま', Meaning: 'Núi' },
    { Word: '富士山', Hiragana: 'ふじさん', Meaning: 'Núi Phú Sĩ' },

    { Word: '川', Hiragana: 'かわ', Meaning: 'Sông' },
    { Word: '大川', Hiragana: 'おおかわ', Meaning: 'Sông lớn' },



    { Word: '天気', Hiragana: 'てんき', Meaning: 'Thời tiết' },
    { Word: '天候', Hiragana: 'てんこう', Meaning: 'Khí hậu' },

    { Word: '気になります', Hiragana: 'きになります', Meaning: 'Tò mò' },
    { Word: '気分', Hiragana: 'きぶん', Meaning: 'Tâm trạng' },

    { Word: '晴れ', Hiragana: 'はれ', Meaning: 'Trời quang đãng' },
    { Word: '晴れます', Hiragana: 'はれます', Meaning: 'Nắng' },

    { Word: '雨', Hiragana: 'あめ', Meaning: 'Mưa' },
    { Word: '大雨', Hiragana: 'おおあめ', Meaning: 'Mưa to' },
    { Word: '雨宿り', Hiragana: 'あまやどり', Meaning: 'Trú mưa' },

    { Word: '雪', Hiragana: 'ゆき', Meaning: 'Tuyết' },
    { Word: '雪だるま', Hiragana: 'ゆきだるま', Meaning: 'Người tuyết' },

    { Word: '雲', Hiragana: 'くも', Meaning: 'Mây' },

    { Word: '風', Hiragana: 'かぜ', Meaning: 'Gió' },
    { Word: '風邪', Hiragana: 'かぜ', Meaning: 'Cảm cúm' },
    { Word: '和風', Hiragana: 'わふう', Meaning: 'Phong cách Nhật Bản' },

    { Word: '空', Hiragana: 'そら', Meaning: 'Bầu trời' },
    { Word: '空気', Hiragana: 'くうき', Meaning: 'Không khí' },
    { Word: '空港', Hiragana: 'くうこう', Meaning: 'Sân bay' },

    // ĐINH ...

    { Word: 'NoKanjiExample', Hiragana: 'NoKanjiExample', Meaning: 'NoKanjiExample' },



    { Word: 'お酒', Hiragana: 'おさけ', Meaning: 'Rượu' },
    { Word: '日本酒', Hiragana: 'にほんしゅ', Meaning: 'Rượu Nhật' },
    { Word: '梅酒', Hiragana: 'うめしゅ', Meaning: 'Rượu mơ' },
    { Word: '作ります', Hiragana: 'つくります', Meaning: 'Làm, tạo ra' },
    { Word: '作文', Hiragana: 'さくぶん', Meaning: 'Đặt câu, viết văn' },
    { Word: '乗り物', Hiragana: 'のりもの', Meaning: 'Phương tiện giao thông' },
    { Word: '博物館', Hiragana: 'はくぶつかん', Meaning: 'Bảo tàng' },
    { Word: '荷物', Hiragana: 'にもつ', Meaning: 'Hành lý' },
    { Word: 'お茶', Hiragana: 'おちゃ', Meaning: 'Trà (Chè)' },
    { Word: '喫茶店', Hiragana: 'きっさてん', Meaning: 'Quán cà phê, tiệm giải khát' },
    { Word: '持ちます', Hiragana: 'もちます', Meaning: 'Cầm, mang / Có, sở hữu' },
    { Word: '持ってきます', Hiragana: 'もってきます', Meaning: 'Mang theo, mang đến' },
    { Word: 'お願いします', Hiragana: 'おねがいします', Meaning: 'Làm ơn, vui lòng (Yêu cầu)' },
    { Word: 'お願い', Hiragana: 'おねがい', Meaning: 'Yêu cầu, điều nhờ vả' },
    { Word: '願い事', Hiragana: 'ねがいごと', Meaning: 'Mong ước, ước nguyện' },

    { Word: '資料', Hiragana: 'しりょう', Meaning: 'Tài liệu' },
    { Word: '料金', Hiragana: 'りょうきん', Meaning: 'Tiền phí' },
    { Word: '理由', Hiragana: 'りゆう', Meaning: 'Lí do' },
    { Word: '無理', Hiragana: 'むり', Meaning: 'Vô lí, quá sức, quá khả năng' },
    { Word: '料理', Hiragana: 'りょうり', Meaning: 'Thức ăn' },
    { Word: '味', Hiragana: 'あじ', Meaning: 'Hương vị' },
    { Word: '地味（な）', Hiragana: 'じみ', Meaning: 'Giản dị, đơn giản' },
    { Word: '色', Hiragana: 'いろ', Meaning: 'Màu sắc' },
    { Word: '色々', Hiragana: 'いろいろ', Meaning: 'Nhiều, phong phú' },
    { Word: '野菜', Hiragana: 'やさい', Meaning: 'Rau' },
    { Word: '中', Hiragana: 'なか', Meaning: 'Bên trong' },
    { Word: '仕事中', Hiragana: 'しごとちゅう', Meaning: 'Đang làm việc' },
    { Word: '中止します', Hiragana: 'ちゅうしします', Meaning: 'Dừng, hủy bỏ, hoãn lại' },
    { Word: '中心', Hiragana: 'ちゅうしん', Meaning: 'Trung tâm' },
    { Word: '一年中', Hiragana: 'いちねんじゅう', Meaning: 'Cả năm' },
    { Word: '入ります', Hiragana: 'はいります', Meaning: 'Đi vào' },
    { Word: '入っています', Hiragana: 'はいっています', Meaning: 'Có chứa, đựng' },
    { Word: '入れます', Hiragana: 'いれます', Meaning: 'Cho vào, bỏ vào' },
    { Word: '入学', Hiragana: 'にゅうがく', Meaning: 'Nhập học' },



    { Word: '会います', Hiragana: 'あいます', Meaning: 'Gặp gỡ' },
    { Word: '二次会', Hiragana: 'にじかい', Meaning: 'Tăng 2' },
    { Word: '社会', Hiragana: 'しゃかい', Meaning: 'Xã hội' },
    { Word: '会社員', Hiragana: 'かいしゃいん', Meaning: 'Nhân viên công ty' },
    { Word: '入社', Hiragana: 'にゅうしゃ', Meaning: 'Việc vào công ty làm' },
    { Word: '本社', Hiragana: 'ほんしゃ', Meaning: 'Trụ sở' },
    { Word: '神社', Hiragana: 'じんじゃ', Meaning: 'Đền thờ' },
    { Word: '支社', Hiragana: 'ししゃ', Meaning: 'Chi nhánh' },
    { Word: '出ます', Hiragana: 'でます', Meaning: 'Đi ra, xuất hiện' },
    { Word: '出かけます', Hiragana: 'でかけます', Meaning: 'Ra ngoài' },
    { Word: '出します', Hiragana: 'だします', Meaning: 'Gửi, đưa ra, nộp' },
    { Word: '出張', Hiragana: 'しゅっちょう', Meaning: 'Công tác' },
    { Word: '出発', Hiragana: 'しゅっぱつ', Meaning: 'Xuất phát' },
    { Word: '発音', Hiragana: 'はつおん', Meaning: 'Phát âm' },
    { Word: '空間', Hiragana: 'くうかん', Meaning: 'Không gian' },
    { Word: '港', Hiragana: 'みなと', Meaning: 'Cảng (biển)' },
    { Word: '着きます', Hiragana: 'つきます', Meaning: 'Đến nơi' },
    { Word: '着ます', Hiragana: 'きます', Meaning: 'Mặc' },
    { Word: '到着', Hiragana: 'とうちゃく', Meaning: 'Đến nơi (hạ cánh)' },

    { Word: '自由', Hiragana: 'じゆう', Meaning: 'Tự do' },
    { Word: '自然', Hiragana: 'しぜん', Meaning: 'Tự nhiên, thiên nhiên' },
    { Word: '車', Hiragana: 'くるま', Meaning: 'Xe ô tô' },
    { Word: '自動車', Hiragana: 'じどうしゃ', Meaning: 'Ô tô' },
    { Word: '自転車', Hiragana: 'じてんしゃ', Meaning: 'Xe đạp' },
    { Word: '電車', Hiragana: 'でんしゃ', Meaning: 'Tàu điện' },
    { Word: '電子レンジ', Hiragana: 'でんしレンジ', Meaning: 'Lò vi sóng' },
    { Word: '電気', Hiragana: 'でんき', Meaning: 'Điện, điện lực, đèn điện' },
    { Word: '電気製品', Hiragana: 'でんきせいひん', Meaning: 'Đồ điện' },
    { Word: '病気', Hiragana: 'びょうき', Meaning: 'Bệnh, ốm' },
    { Word: '人気', Hiragana: 'にんき', Meaning: 'Được yêu thích, ưa chuộng' },
    { Word: '使います', Hiragana: 'つかいます', Meaning: 'Sử dụng' },
    { Word: '大使館', Hiragana: 'たいしかん', Meaning: 'Đại sứ quán' },
    { Word: '借ります', Hiragana: 'かります', Meaning: 'Vay, mượn' },
    { Word: '送ります', Hiragana: 'おくります', Meaning: 'Đưa, tiễn, gửi đi' },



    { Word: '体', Hiragana: 'からだ', Meaning: 'Cơ thể' },
    { Word: '全体', Hiragana: 'ぜんたい', Meaning: 'Toàn bộ các phần' },
    { Word: '頭', Hiragana: 'あたま', Meaning: 'Đầu' },
    { Word: '目', Hiragana: 'め', Meaning: 'Mắt' },
    { Word: '目次', Hiragana: 'もくじ', Meaning: 'Phụ lục' },
    { Word: '耳', Hiragana: 'みみ', Meaning: 'Tai' },
    { Word: '上', Hiragana: 'うえ', Meaning: 'Bên / phía trên' },
    { Word: '上手', Hiragana: 'じょうず', Meaning: 'Giỏi' },
    { Word: '下', Hiragana: 'した', Meaning: 'Bên / phía dưới' },
    { Word: '下手', Hiragana: 'へた', Meaning: 'Kém' },
    { Word: '手', Hiragana: 'て', Meaning: 'Tay' },
    { Word: '歌手', Hiragana: 'かしゅ', Meaning: 'Ca sĩ' },

    { Word: '運転手', Hiragana: 'うんてんしゅ', Meaning: 'Tài xế' },
    { Word: '苦手', Hiragana: 'にがて', Meaning: 'Kém, yếu, không hợp, sợ' },
    { Word: '選手', Hiragana: 'せんしゅ', Meaning: 'Tuyển thủ' },
    { Word: '足', Hiragana: 'あし', Meaning: 'Chân' },
    { Word: '足ります', Hiragana: 'たります', Meaning: 'Đủ' },
    { Word: '二足', Hiragana: 'にそく', Meaning: '2 đôi (giày, tất,..)' },
    { Word: '毎日', Hiragana: 'まいにち', Meaning: 'Mỗi ngày' },
    { Word: '毎週', Hiragana: 'まいしゅう', Meaning: 'Mỗi tuần' },
    { Word: '週末', Hiragana: 'しゅうまつ', Meaning: 'Cuối tuần' },
    { Word: '元気', Hiragana: 'げんき', Meaning: 'Khỏe mạnh' },
    { Word: '起きます', Hiragana: 'おきます', Meaning: 'Thức dậy' },
    { Word: '歩きます', Hiragana: 'あるきます', Meaning: 'Đi bộ' },
    { Word: '散歩します', Hiragana: 'さんぽします', Meaning: 'Đi dạo' },
    { Word: '走ります', Hiragana: 'はしります', Meaning: 'Chạy' },
    { Word: '泳ぎます', Hiragana: 'およぎます', Meaning: 'Bơi' },
    { Word: '外食', Hiragana: 'がいしょく', Meaning: 'Ăn ở ngoài' },



    { Word: 'お祝い', Hiragana: 'おいわい', Meaning: 'Sự chúc mừng' },
    { Word: '誕生日', Hiragana: 'たんじょうび', Meaning: 'Sinh nhật' },
    { Word: '結びます', Hiragana: 'むすびます', Meaning: 'Buộc' },
    { Word: '結婚します', Hiragana: 'けっこんします', Meaning: 'Kết hôn' },
    { Word: '離婚します', Hiragana: 'りこんします', Meaning: 'Ly hôn' },
    { Word: '絵', Hiragana: 'え', Meaning: 'Bức tranh' },
    { Word: '写ります', Hiragana: 'うつります', Meaning: 'Chụp lại, copy lại' },
    { Word: '真面目', Hiragana: 'まじめ', Meaning: 'Nghiêm túc' },
    { Word: '写真', Hiragana: 'しゃしん', Meaning: 'Bức ảnh' },
    { Word: '真実', Hiragana: 'しんじつ', Meaning: 'Sự thật' },
    { Word: '計ります', Hiragana: 'はかります', Meaning: 'Cân đo' },
    { Word: '会計', Hiragana: 'かいけい', Meaning: 'Kế toán, tính toán, thanh toán' },
    { Word: '家', Hiragana: 'いえ', Meaning: 'Nhà' },
    { Word: '家族', Hiragana: 'かぞく', Meaning: 'Gia đình' },
    { Word: '作家', Hiragana: 'さっか', Meaning: 'Tác giả' },
    { Word: '画家', Hiragana: 'がか', Meaning: 'Họa sĩ' },
    { Word: '思います', Hiragana: 'おもいます', Meaning: 'Nghĩ' },
    { Word: '去年', Hiragana: 'きょねん', Meaning: 'Năm ngoái' },



    { Word: '自己紹介', Hiragana: 'じこしょうかい', Meaning: 'Giới thiệu bản thân' },
    { Word: '介護', Hiragana: 'かいご', Meaning: 'Điều dưỡng' },
    { Word: '名前', Hiragana: 'なまえ', Meaning: 'Tên' },
    { Word: '名字', Hiragana: 'みょうじ', Meaning: 'Họ' },
    { Word: '有名', Hiragana: 'ゆうめい', Meaning: 'Nổi tiếng' },
    { Word: '意思', Hiragana: 'いし', Meaning: 'Ý chí' },
    { Word: '意味', Hiragana: 'いみ', Meaning: 'Ý nghĩa' },
    { Word: '部屋', Hiragana: 'へや', Meaning: 'Căn phòng' },
    { Word: '本屋', Hiragana: 'ほんや', Meaning: 'Tiệm sách' },
    { Word: '寿司屋', Hiragana: 'すしや', Meaning: 'Tiệm sushi' },
    { Word: '近い', Hiragana: 'ちかい', Meaning: 'Gần' },
    { Word: '近所', Hiragana: 'きんじょ', Meaning: 'Hàng xóm, lân cận' },
    { Word: '最近', Hiragana: 'さいきん', Meaning: 'Gần đây' },
    { Word: '住みます', Hiragana: 'すみます', Meaning: 'Sinh sống' },
    { Word: '住所', Hiragana: 'じゅうしょ', Meaning: 'Địa chỉ' },
    { Word: '働きます', Hiragana: 'はたらきます', Meaning: 'Làm việc' },
    { Word: '一番', Hiragana: 'いちばん', Meaning: 'Nhất, đầu tiên, số một' },
    { Word: '一番目', Hiragana: 'いちばんめ', Meaning: 'Thứ nhất' },

    { Word: '兄', Hiragana: 'あに', Meaning: 'Anh trai (mình)' },
    { Word: 'お兄さん', Hiragana: 'おにいさん', Meaning: 'Anh trai (người khác)/gọi' },
    { Word: '兄弟', Hiragana: 'きょうだい', Meaning: 'Anh em trai' },
    { Word: '姉', Hiragana: 'あね', Meaning: 'Chị gái (mình)' },
    { Word: 'お姉さん', Hiragana: 'おねえさん', Meaning: 'Chị gái (người khác)/gọi' },
    { Word: '姉妹', Hiragana: 'しまい', Meaning: 'Chị em gái' },
    { Word: '水族館', Hiragana: 'すいぞくかん', Meaning: 'Thuỷ cung' },
    { Word: '民族', Hiragana: 'みんぞく', Meaning: 'Dân tộc' },
    { Word: '長い', Hiragana: 'ながい', Meaning: 'Dài' },
    { Word: '長所', Hiragana: 'ちょうしょ', Meaning: 'Sở trường' },
    { Word: '成長', Hiragana: 'せいちょう', Meaning: 'Sự phát triển' },
    { Word: '長生き', Hiragana: 'ながいき', Meaning: 'Sống lâu, trường thọ' },
    { Word: '短い', Hiragana: 'みじかい', Meaning: 'Ngắn' },
    { Word: '短文', Hiragana: 'たんぶん', Meaning: 'Đoạn văn ngắn' },
    { Word: '短所', Hiragana: 'たんしょ', Meaning: 'Sở đoản' },
    { Word: '低い', Hiragana: 'ひくい', Meaning: 'Thấp' },
    { Word: '歌', Hiragana: 'うた', Meaning: 'Bài hát' },
    { Word: '歌います', Hiragana: 'うたいます', Meaning: 'Hát' },



    { Word: 'お客さん', Hiragana: 'おきゃくさん', Meaning: 'Khách hàng' },
    { Word: '注ぎます', Hiragana: 'つぎます', Meaning: 'Rót (nước, rượu,..)' },
    { Word: '注意します', Hiragana: 'ちゅういします', Meaning: 'Chú ý' },
    { Word: '注文します', Hiragana: 'ちゅうもんします', Meaning: 'Gọi đồ, Oder' },
    { Word: '洋服', Hiragana: 'ようふく', Meaning: 'Quần áo kiểu Âu' },
    { Word: '洋食', Hiragana: 'ようしょく', Meaning: 'Đồ ăn Tây' },
    { Word: '和食', Hiragana: 'わしょく', Meaning: 'Đồ ăn Nhật' },
    { Word: '和服', Hiragana: 'わふく', Meaning: 'Quần áo kiểu Nhật' },
    { Word: '和室', Hiragana: 'わしつ', Meaning: 'Phòng kiểu Nhật' },
    { Word: '平和', Hiragana: 'へいわ', Meaning: 'Hoà bình' },
    { Word: '心地', Hiragana: 'こころち', Meaning: 'Nhà' },
    { Word: '地味', Hiragana: 'じみ', Meaning: 'Giản dị' },
    { Word: '方', Hiragana: 'かた', Meaning: 'Vị (người)' },
    { Word: '～方', Hiragana: '～かた', Meaning: 'Cách làm...' },
    { Word: '地方', Hiragana: 'ちほう', Meaning: 'Địa phương' },
    { Word: '方法', Hiragana: 'ほうほう', Meaning: 'Phương pháp, cách thức' },
    { Word: '有料', Hiragana: 'ゆうりょう', Meaning: 'Có phí, mất phí' },
    { Word: '牛乳', Hiragana: 'ぎゅうにゅう', Meaning: 'Sữa bò' },
    { Word: '冷たい', Hiragana: 'つめたい', Meaning: 'Lạnh (cảm giác)' },
    { Word: '冷やします', Hiragana: 'ひやします', Meaning: 'Làm lạnh' },
    { Word: '冷えます', Hiragana: 'ひえます', Meaning: 'Nguội đi' },
    { Word: '冷蔵庫', Hiragana: 'れいぞうこ', Meaning: 'Tủ lạnh' },

    { Word: '飯', Hiragana: 'めし', Meaning: 'Cơm' },
    { Word: 'ご飯', Hiragana: 'ごはん', Meaning: 'Bữa cơm' },
    { Word: '塩', Hiragana: 'しお', Meaning: 'Muối' },
    { Word: '全て', Hiragana: 'すべて', Meaning: 'Tất cả' },
    { Word: '全然', Hiragana: 'ぜんぜん', Meaning: 'Hoàn toàn' },
    { Word: '全部', Hiragana: 'ぜんぶ', Meaning: 'Toàn bộ' },
    { Word: '熱い', Hiragana: 'あつい', Meaning: 'Nóng' },
    { Word: '熱', Hiragana: 'ねつ', Meaning: 'Sốt' },
    { Word: '苦い', Hiragana: 'にがい', Meaning: 'Đắng' },
    { Word: '苦しい', Hiragana: 'くるしい', Meaning: 'Đau khổ' },



    { Word: '森', Hiragana: 'もり', Meaning: 'Rừng' },
    { Word: '島', Hiragana: 'しま', Meaning: 'Đảo' },
    { Word: '船', Hiragana: 'ふね', Meaning: 'Con thuyền' },
    { Word: '暑い', Hiragana: 'あつい', Meaning: 'Nóng' },
    { Word: '暑中', Hiragana: 'しょちゅう', Meaning: 'Giữa hè' },
    { Word: '帰ります', Hiragana: 'かえります', Meaning: 'trở về' },
    { Word: '帰国', Hiragana: 'きこく', Meaning: 'Về nước' },
    { Word: '予定', Hiragana: 'よてい', Meaning: 'Dự định' },
    { Word: '予算', Hiragana: 'よさん', Meaning: 'Dự toán' },
    { Word: '予約', Hiragana: 'よやく', Meaning: 'Đặt trước' },
    { Word: '約束', Hiragana: 'やくそく', Meaning: 'Lời hứa, cuộc hẹn' },
    { Word: '運', Hiragana: 'うん', Meaning: 'Vận mệnh' },
    { Word: '運動', Hiragana: 'うんどう', Meaning: 'Vận động' },
    { Word: '転びます', Hiragana: 'ころびます', Meaning: 'Ngã' },
    { Word: '運転します', Hiragana: 'うんてんします', Meaning: 'Lái xe' },

    { Word: '観ます', Hiragana: 'みます', Meaning: 'Xem (quan sát)' },
    { Word: '観光地', Hiragana: 'かんこうち', Meaning: 'Địa điểm tham quan, du lịch' },
    { Word: '光ります', Hiragana: 'ひかります', Meaning: 'Toả sáng' },
    { Word: '光', Hiragana: 'ひかり', Meaning: 'Ánh sáng' },
    { Word: '観光', Hiragana: 'かんこう', Meaning: 'Tham quan, du lịch' },
    { Word: '男性', Hiragana: 'だんせい', Meaning: 'Đàn ông, nam giới' },
    { Word: '女性', Hiragana: 'じょせい', Meaning: 'Phụ nữ, nữ giới' },
    { Word: '性格', Hiragana: 'せいかく', Meaning: 'Tính cách' },
    { Word: '動きます', Hiragana: 'うごきます', Meaning: 'Chuyển động, hoạt động' },
    { Word: '活動', Hiragana: 'かつどう', Meaning: 'Hoạt động' },
    { Word: '運動会', Hiragana: 'うんどうかい', Meaning: 'Hội thao' },
    { Word: '動作', Hiragana: 'どうさ', Meaning: 'Động tác' },
    { Word: '動物', Hiragana: 'どうぶつ', Meaning: 'Động vật' },
    { Word: '動物園', Hiragana: 'どうぶつえん', Meaning: 'Sở thú' },
    { Word: '入場料', Hiragana: 'にゅうじょうりょう', Meaning: 'Phí vào cửa' },
    { Word: '無料', Hiragana: 'むりょう', Meaning: 'Miễn phí' },
    { Word: '無い', Hiragana: 'ない', Meaning: 'Không có' },
    { Word: '無口', Hiragana: 'むぐち', Meaning: 'Ít nói' },
    { Word: '明るい', Hiragana: 'あかるい', Meaning: 'Sáng sủa' },
    { Word: '明日', Hiragana: 'あした', Meaning: 'Ngày mai' },
    { Word: '説明', Hiragana: 'せつめい', Meaning: 'Giải thích' },
    { Word: '便利', Hiragana: 'べんり', Meaning: 'Tiện lợi' },
    { Word: '不便', Hiragana: 'ふべん', Meaning: 'Bất tiện' },
    { Word: '利用', Hiragana: 'りよう', Meaning: 'Tận dụng' },








    { Word: '受けます', Hiragana: 'うけます', Meaning: 'Tiếp nhận, nhận, tham dự, tham gia' },
    { Word: '受かります', Hiragana: 'うかります', Meaning: 'Đỗ (đỗ đạt)' },
    { Word: '付けます', Hiragana: 'つけます', Meaning: 'Đính vào, thêm vào' },
    { Word: '受付', Hiragana: 'うけつけ', Meaning: 'Quầy lễ tân' },
    { Word: '広い', Hiragana: 'ひろい', Meaning: 'Rộng' },
    { Word: '広げます', Hiragana: 'ひろげます', Meaning: 'Làm rộng ra' },
    { Word: '広がります', Hiragana: 'ひろがります', Meaning: 'Rộng ra, được mở rộng ra' },
    { Word: '広告', Hiragana: 'こうこく', Meaning: 'Quảng cáo' },
    { Word: '公園', Hiragana: 'こうえん', Meaning: 'Công viên' },
    { Word: '広場', Hiragana: 'ひろば', Meaning: 'Quảng trường' },
    { Word: '会場', Hiragana: 'かいじょう', Meaning: 'Hội trường, địa điểm tổ chức' },
    { Word: '場所', Hiragana: 'ばしょ', Meaning: 'Địa điểm' },
    { Word: '工場', Hiragana: 'こうじょう', Meaning: 'Công trường' },
    { Word: '問います', Hiragana: 'といます', Meaning: 'Hỏi' },
    { Word: '質問', Hiragana: 'しつもん', Meaning: 'Câu hỏi' },
    { Word: '宿題', Hiragana: 'しゅくだい', Meaning: 'Bài tập' },
    { Word: '問題', Hiragana: 'もんだい', Meaning: 'Vấn đề, câu hỏi' },
    { Word: '同じ', Hiragana: 'おなじ', Meaning: 'Giống nhau' },
    { Word: '同意', Hiragana: 'どうい', Meaning: 'Đồng ý' },
    { Word: '集めます', Hiragana: 'あつめます', Meaning: 'Tập hợp lại, tập trung lại, sưu tầm' },
    { Word: '集まります', Hiragana: 'あつまります', Meaning: 'Tụ họp, tập trung' },
    { Word: '募集', Hiragana: 'ぼしゅう', Meaning: 'Tuyển dụng' },
    { Word: '集中します', Hiragana: 'しゅうちゅうします', Meaning: 'Tập trung' },
    { Word: '始めます', Hiragana: 'はじめます', Meaning: 'Bắt đầu' },
    { Word: '始まります', Hiragana: 'はじまります', Meaning: 'Được bắt đầu' },
    { Word: '年始', Hiragana: 'ねんし', Meaning: 'Đầu năm' },
    { Word: '終わります', Hiragana: 'おわります', Meaning: 'Kết thúc' },
    { Word: '終了', Hiragana: 'しゅうりょう', Meaning: 'Kết thúc, hoàn thành' },
    { Word: '止めます', Hiragana: 'とめます', Meaning: 'Dừng lại' },
    { Word: '止まります', Hiragana: 'とまります', Meaning: 'Dừng lại' },
    { Word: '中止', Hiragana: 'ちゅうし', Meaning: 'Dừng, hủy bỏ, hoãn lại' },
    { Word: '禁止', Hiragana: 'きんし', Meaning: 'Cấm' },
    { Word: '教えます', Hiragana: 'おしえます', Meaning: 'Dạy, chỉ dẫn' },
    { Word: '教わります', Hiragana: 'おそわります', Meaning: 'Được chỉ dạy' },
    { Word: '教師', Hiragana: 'きょうし', Meaning: 'Giáo viên' },
    { Word: '教会', Hiragana: 'きょうかい', Meaning: 'Nhà thờ' },
    { Word: '仏教', Hiragana: 'ぶっきょう', Meaning: 'Phật giáo' },

    { Word: '祭り', Hiragana: 'まつり', Meaning: 'Lễ hội' },
    { Word: '参ります', Hiragana: 'まいります', Meaning: 'Thăm, đi đến' },
    { Word: '参加します', Hiragana: 'さんかします', Meaning: 'Tham gia' },
    { Word: '若者', Hiragana: 'わかもの', Meaning: 'Người trẻ' },
    { Word: '参加者', Hiragana: 'さんかしゃ', Meaning: 'Người tham gia' },
    { Word: '研究者', Hiragana: 'けんきゅうしゃ', Meaning: 'Nhà nghiên cứu' },
    { Word: '急ぎます', Hiragana: 'いそぎます', Meaning: 'Vội, gấp' },
    { Word: '救急車', Hiragana: 'きゅうきゅうしゃ', Meaning: 'Xe cấp cứu' },
    { Word: '決めます', Hiragana: 'きめます', Meaning: 'Quyết định' },
    { Word: '決意', Hiragana: 'けつい', Meaning: 'Ý chí' },
    { Word: '決心', Hiragana: 'けっしん', Meaning: 'Quyết tâm' },
    { Word: '知ります', Hiragana: 'しります', Meaning: 'Biết' },
    { Word: 'お知らせ', Hiragana: 'おしらせ', Meaning: 'Thông báo' },
    { Word: '知識', Hiragana: 'ちしき', Meaning: 'Kiến thức' },
    { Word: '知り合い', Hiragana: 'しりあい', Meaning: 'Người quen' },



    { Word: '正月', Hiragana: 'しょうがつ', Meaning: 'Tết' },
    { Word: '正しい', Hiragana: 'ただしい', Meaning: 'Đúng' },
    { Word: '正解', Hiragana: 'せいかい', Meaning: 'Chính xác' },
    { Word: '正社員', Hiragana: 'せいしゃいん', Meaning: 'Nhân viên chính thức' },
    { Word: '年末', Hiragana: 'ねんまつ', Meaning: 'Cuối năm' },
    { Word: '父親', Hiragana: 'ちちおや', Meaning: 'Bố' },
    { Word: '母親', Hiragana: 'ははおや', Meaning: 'Mẹ' },
    { Word: '両親', Hiragana: 'りょうしん', Meaning: 'Bố mẹ' },
    { Word: '親しい', Hiragana: 'したしい', Meaning: 'Thân thiện, thân thiết, gần gũi' },
    { Word: '親切', Hiragana: 'しんせつ', Meaning: 'Tốt bụng' },
    { Word: '忙しい', Hiragana: 'いそがしい', Meaning: 'Bận rộn' },
    { Word: '特に', Hiragana: 'とくに', Meaning: 'Đặc biệt là ~' },
    { Word: '別れます', Hiragana: 'わかれます', Meaning: 'Chia tay' },
    { Word: '特別', Hiragana: 'とくべつ', Meaning: 'Đặc biệt' },
    { Word: '喜びます', Hiragana: 'よろこびます', Meaning: 'Hạnh phúc, vui sướng' },

    { Word: '幸せ', Hiragana: 'しあわせ', Meaning: 'Hạnh phúc' },
    { Word: '不幸', Hiragana: 'ふこう', Meaning: 'Bất hạnh' },
    { Word: '成人', Hiragana: 'せいじん', Meaning: 'Người trưởng thành' },
    { Word: '成人式', Hiragana: 'せいじんしき', Meaning: 'Lễ trưởng thành' },
    { Word: '成功', Hiragana: 'せいこう', Meaning: 'Thành công' },
    { Word: '事', Hiragana: 'こと', Meaning: 'Việc gì đó' },
    { Word: '仕事', Hiragana: 'しごと', Meaning: 'Công việc' },
    { Word: '合います', Hiragana: 'あいます', Meaning: 'Hợp' },
    { Word: '合わせます', Hiragana: 'あわせます', Meaning: 'Hợp lại, hoà trộn lại' },
    { Word: '合格', Hiragana: 'ごうかく', Meaning: 'Đỗ đạt' },
    { Word: '試します', Hiragana: 'ためします', Meaning: 'Thử' },
    { Word: '試合', Hiragana: 'しあい', Meaning: 'Trận đấu' },
    { Word: '試験', Hiragana: 'しけん', Meaning: 'Kỳ thi' },
    { Word: '経験', Hiragana: 'けいけん', Meaning: 'Kinh nghiệm' },
    { Word: '式', Hiragana: 'しき', Meaning: 'Nghi lễ' },
    { Word: '卒業式', Hiragana: 'そつぎょうしき', Meaning: 'Lễ tốt nghiệp' },
    { Word: '市場', Hiragana: 'いちば', Meaning: 'Chợ' },
    { Word: '都市', Hiragana: 'とし', Meaning: 'Thành phố' },



    { Word: '商売', Hiragana: 'しょうばい', Meaning: 'Buôn bán' },
    { Word: '品物', Hiragana: 'しなもの', Meaning: 'Hàng hoá' },
    { Word: '商品', Hiragana: 'しょうひん', Meaning: 'Sản phẩm, hàng hoá' },
    { Word: '日本製', Hiragana: 'にほんせい', Meaning: 'Sản xuất tại Nhật Bản' },
    { Word: '作製', Hiragana: 'さくせい', Meaning: 'Sự sản xuất; sự chế tác' },
    { Word: 'そうじ機', Hiragana: 'そうじき', Meaning: 'Máy hút bụi' },
    { Word: '機能', Hiragana: 'きのう', Meaning: 'Chức năng' },
    { Word: 'ご機嫌', Hiragana: 'ごきげん', Meaning: 'Sức khỏe (kính ngữ)' },
    { Word: '機会', Hiragana: 'きかい', Meaning: 'Cơ hội' },
    { Word: '店員', Hiragana: 'てんいん', Meaning: 'Nhân viên cửa hàng' },
    { Word: '銀行員', Hiragana: 'ぎんこういん', Meaning: 'Nhân viên ngân hàng' },
    { Word: '調べます', Hiragana: 'しらべます', Meaning: 'Tra cứu' },
    { Word: '体調', Hiragana: 'たいちょう', Meaning: 'Tình trạng cơ thể' },
    { Word: '調味料', Hiragana: 'ちょうみりょう', Meaning: 'Gia vị' },
    { Word: '調子', Hiragana: 'ちょうし', Meaning: 'Tình trạng' },
    { Word: '悪い', Hiragana: 'わるい', Meaning: 'Xấu' },
    { Word: '調子が悪い', Hiragana: 'ちょうしがわるい', Meaning: 'Hoạt động không tốt, trục trặc' },
    { Word: '悪魔', Hiragana: 'あくま', Meaning: 'Ác ma' },
    { Word: '考えます', Hiragana: 'かんがえます', Meaning: 'Suy nghĩ' },
    { Word: '考え', Hiragana: 'かんがえ', Meaning: 'Suy nghĩ' },
    { Word: '参考します', Hiragana: 'さんこうします', Meaning: 'Tham khảo' },

    { Word: '可能性', Hiragana: 'かのうせい', Meaning: 'Có khả năng' },
    { Word: '能力', Hiragana: 'のうりょく', Meaning: 'Năng lực' },
    { Word: '省エネ', Hiragana: 'しょうエネ', Meaning: 'Tiết kiệm năng lượng' },
    { Word: '反省します', Hiragana: 'はんせいします', Meaning: 'Kiểm điểm lại mình' },
    { Word: '帰省', Hiragana: 'きせい', Meaning: 'Sự về quê hương' },
    { Word: '重い', Hiragana: 'おもい', Meaning: 'Nặng' },
    { Word: '重要', Hiragana: 'じゅうよう', Meaning: 'Quan trọng' },
    { Word: '体重', Hiragana: 'たいじゅう', Meaning: 'Cân nặng' },
    { Word: '軽い', Hiragana: 'かるい', Meaning: 'Nhẹ' },
    { Word: '気軽', Hiragana: 'きがる', Meaning: 'Thoải mái, dễ chịu' },
    { Word: '静か', Hiragana: 'しずか', Meaning: 'Yên tĩnh' },
    { Word: '冷静', Hiragana: 'れいせい', Meaning: 'Bình tĩnh, điềm tĩnh' },
    { Word: '早い', Hiragana: 'はやい', Meaning: 'Sớm' },
    { Word: '洗います', Hiragana: 'あらいます', Meaning: 'Giặt' },
    { Word: 'お手洗い', Hiragana: 'おてあらい', Meaning: 'Bồn; chậu rửa tay; nhà vệ sinh' },
    { Word: '洗濯します', Hiragana: 'せんたくします', Meaning: 'Giặt rũ' },
    { Word: '満足', Hiragana: 'まんぞく', Meaning: 'Mãn nguyện' },
    { Word: '不満', Hiragana: 'ふまん', Meaning: 'Bất mãn' },



    { Word: '神さま', Hiragana: 'かみさま', Meaning: 'Thần thánh' },
    { Word: '精神', Hiragana: 'せいしん', Meaning: 'Thần kinh' },
    { Word: '社長', Hiragana: 'しゃちょう', Meaning: 'Giám đốc' },
    { Word: 'お寺', Hiragana: 'おてら', Meaning: 'Chùa' },
    { Word: '寺参り', Hiragana: 'てらまいり', Meaning: 'Việc viếng chùa' },
    { Word: '歴史', Hiragana: 'れきし', Meaning: 'Lịch sử' },
    { Word: '履歴書', Hiragana: 'りれきしょ', Meaning: 'Sơ yếu lý lịch' },
    { Word: '学歴', Hiragana: 'がくれき', Meaning: 'Học vấn' },
    { Word: '歴史的', Hiragana: 'れきしてき', Meaning: 'Mang tính lịch sử' },
    { Word: '世紀', Hiragana: 'せいき', Meaning: 'Thế kỷ' },
    { Word: '世の中', Hiragana: 'よのなか', Meaning: 'Trong thế giới này' },
    { Word: '世代', Hiragana: 'せだい', Meaning: 'Thời đại' },
    { Word: '世界', Hiragana: 'せかい', Meaning: 'Thế giới' },
    { Word: '限界', Hiragana: 'げんかい', Meaning: 'Giới hạn' },
    { Word: '心', Hiragana: 'こころ', Meaning: 'Trái tim, tấm lòng' },
    { Word: '目的', Hiragana: 'もくてき', Meaning: 'Mục đích' },
    { Word: '伝統的', Hiragana: 'でんとうてき', Meaning: 'Mang tính truyền thống' },
    { Word: '日本的', Hiragana: 'にほんてき', Meaning: 'Mang tính Nhật Bản' },

    { Word: '説得', Hiragana: 'せっとく', Meaning: 'Thuyết phục' },
    { Word: '小説', Hiragana: 'しょうせつ', Meaning: 'Tiểu thuyết' },
    { Word: '家具', Hiragana: 'かぐ', Meaning: 'Dụng cụ gia đình' },
    { Word: '道具', Hiragana: 'どうぐ', Meaning: 'Dụng cụ nói chung' },
    { Word: '博士', Hiragana: 'はかせ', Meaning: 'Tiến sĩ' },
    { Word: '旅館', Hiragana: 'りょかん', Meaning: 'Quán trọ (du lịch)' },
    { Word: '必ず', Hiragana: 'かならず', Meaning: 'Nhất định' },
    { Word: '要ります', Hiragana: 'いります', Meaning: 'Cần' },
    { Word: '必要', Hiragana: 'ひつよう', Meaning: 'Cần thiết' },
    { Word: '階段', Hiragana: 'かいだん', Meaning: 'Cầu thang bộ' },
    { Word: '一階', Hiragana: 'いっかい', Meaning: 'Tầng 1' },
    { Word: '二階', Hiragana: 'にかい', Meaning: 'Tầng 2' },
    { Word: '三階', Hiragana: 'さんがい', Meaning: 'Tầng 3' },



    { Word: '油', Hiragana: 'あぶら', Meaning: 'Dầu (dầu ăn)' },
    { Word: '差し油', Hiragana: 'さしあぶら', Meaning: 'Dầu để tra (vào máy)' },
    { Word: '紙', Hiragana: 'かみ', Meaning: 'Giấy' },
    { Word: '紙皿', Hiragana: 'かみざら', Meaning: 'Đĩa giấy' },
    { Word: '温かい', Hiragana: 'あたたかい', Meaning: 'Ấm (thời tiết)' },
    { Word: '低温', Hiragana: 'ていおん', Meaning: 'Nhiệt độ thấp' },
    { Word: '体温', Hiragana: 'たいおん', Meaning: 'Nhiệt độ cơ thể; thân nhiệt' },
    { Word: '体温計', Hiragana: 'たいおんけい', Meaning: 'Nhiệt kế' },
    { Word: '温泉', Hiragana: 'おんせん', Meaning: 'Suối nước nóng' },
    { Word: 'この度', Hiragana: 'このたび', Meaning: 'Nhân dịp này' },
    { Word: '丁度', Hiragana: 'ちょうど', Meaning: 'Vừa đúng; vừa chuẩn' },
    { Word: '二度', Hiragana: 'にど', Meaning: '2 lần; 2 độ' },
    { Word: '温度', Hiragana: 'おんど', Meaning: 'Nhiệt độ' },
    { Word: '温度を上げます', Hiragana: 'おんどをあげます', Meaning: 'Tăng nhiệt độ' },
    { Word: '今度', Hiragana: 'こんど', Meaning: 'Lần tới' },
    { Word: '活かします', Hiragana: 'いかします', Meaning: 'Tận dụng tối đa khả năng và hiệu suất' },
    { Word: '生活', Hiragana: 'せいかつ', Meaning: 'Cuộc sống sinh hoạt' },
    { Word: '復活', Hiragana: 'ふっかつ', Meaning: 'Bình phục, hồi phục' },
    { Word: '活発', Hiragana: 'かっぱつ', Meaning: 'Hoạt bát' },
    { Word: '不思議', Hiragana: 'ふしぎ', Meaning: 'Kỳ lạ' },
    { Word: '議論', Hiragana: 'ぎろん', Meaning: 'Tranh luận' },
    { Word: '事務室', Hiragana: 'じむしつ', Meaning: 'Văn phòng' },
    { Word: '会議室', Hiragana: 'かいぎしつ', Meaning: 'Phòng họp' },
    { Word: '寒い', Hiragana: 'さむい', Meaning: 'Lạnh (thời tiết)' },
    { Word: '～点', Hiragana: '～てん', Meaning: '～ Điểm' },
    { Word: '点数', Hiragana: 'てんすう', Meaning: 'Điểm số' },
    { Word: '注意点', Hiragana: 'ちゅういてん', Meaning: 'Điểm chú ý' },

    { Word: '服', Hiragana: 'ふく', Meaning: 'Quần áo' },
    { Word: '売ります', Hiragana: 'うります', Meaning: 'Bán' },
    { Word: '売れます', Hiragana: 'うれます', Meaning: 'Bán chạy' },
    { Word: '安売ります', Hiragana: 'やすうります', Meaning: 'Bán đổ bán tháo' },
    { Word: '売上', Hiragana: 'うりあげ', Meaning: 'Doanh thu, tiền lãi' },
    { Word: '貸します', Hiragana: 'かします', Meaning: 'Cho mượn' },
    { Word: '賃貸', Hiragana: 'ちんたい', Meaning: 'Sự cho thuê' },
    { Word: '返します', Hiragana: 'かえします', Meaning: 'Trả lại' },
    { Word: '返事', Hiragana: 'へんじ', Meaning: 'Sự trả lời, hồi âm' },
    { Word: '返信', Hiragana: 'へんしん', Meaning: 'Sự trả lời, hồi âm' },
    { Word: '変わります', Hiragana: 'かわります', Meaning: 'Được thay đổi' },
    { Word: '変えます', Hiragana: 'かえます', Meaning: 'Thay đổi' },
    { Word: '変更します', Hiragana: 'へんこうします', Meaning: 'Biến đổi, thay đổi, dịch chuyển' },
    { Word: '変', Hiragana: 'へん', Meaning: 'Kì lạ' },
    { Word: '用います', Hiragana: 'もちいます', Meaning: 'Áp dụng cho' },
    { Word: '使用します', Hiragana: 'しようします', Meaning: 'Sử dụng' },
    { Word: '利用します', Hiragana: 'りようする', Meaning: 'Tận dụng' },
    { Word: '子供用', Hiragana: 'こどもよう', Meaning: 'Sử dụng cho trẻ con' },




    { Word: 'NoKanjiExample', Hiragana: 'NoKanjiExample', Meaning: 'NoKanjiExample' },
    { Word: 'NoKanjiExample', Hiragana: 'NoKanjiExample', Meaning: 'NoKanjiExample' },
    { Word: 'NoKanjiExample', Hiragana: 'NoKanjiExample', Meaning: 'NoKanjiExample' },
    { Word: 'NoKanjiExample', Hiragana: 'NoKanjiExample', Meaning: 'NoKanjiExample' },
];

export const Verb = [
    { Hiragana: 'NoVerb', Kanji: 'NoVerb', Group: 'NoVerb', Meaning: 'NoVerb', Special: 'false' },
    // さんします
    // つくります
    // つぎます
    // たのしみます
    // かんこうします
    // ドライブします
    // レンタルします
    // よやくします
    // うんてんします
    // おもいます
    // つれます

    // なります

    // なげます
    // いのります
    // ねがいます
    // いわいます
    // かんしゃします
    // せいちょうします
    // しゅうかくします
    // まめまきます


    //「い」ます
    { Hiragana: 'いきます', Kanji: '行きます', Group: 'I', Meaning: 'Đi', Special: 'true' },
    { Hiragana: 'あいます', Kanji: '会います', Group: 'I', Meaning: 'Gặp', Special: 'false' },
    { Hiragana: 'のみます', Kanji: '飲みます', Group: 'I', Meaning: 'Uống', Special: 'false' },
    { Hiragana: 'とります', Kanji: '取ります', Group: 'I', Meaning: 'Lấy', Special: 'false' },
    { Hiragana: 'かいます', Kanji: '買います', Group: 'I', Meaning: 'Mua', Special: 'false' },
    { Hiragana: 'もちます', Kanji: '持ちます', Group: 'I', Meaning: 'Cầm nắm', Special: 'false' },
    { Hiragana: 'まちます', Kanji: '待ちます', Group: 'I', Meaning: 'Chờ', Special: 'false' },
    { Hiragana: 'とまります', Kanji: '止まります', Group: 'I', Meaning: 'Dừng lại', Special: 'false' },
    { Hiragana: 'かえります', Kanji: '帰り', Group: 'I', Meaning: 'Về', Special: 'false' },
    { Hiragana: 'よみます', Kanji: '読みます', Group: 'I', Meaning: 'Đọc', Special: 'false' },
    { Hiragana: 'あそびます', Kanji: '遊びます', Group: 'I', Meaning: 'Đi chơi', Special: 'false' },
    { Hiragana: 'しにます', Kanji: '死にます', Group: 'I', Meaning: 'Chết', Special: 'false' },
    { Hiragana: 'かきます', Kanji: '書きます', Group: 'I', Meaning: 'Viết', Special: 'false' },
    { Hiragana: 'ききます', Kanji: '聞きます', Group: 'I', Meaning: 'Nghe, hỏi', Special: 'false' },
    { Hiragana: 'およぎます', Kanji: '泳ぎます', Group: 'I', Meaning: 'Bơi', Special: 'false' },
    { Hiragana: 'はなします', Kanji: '話します', Group: 'I', Meaning: 'Nói chuyện', Special: 'false' },
    { Hiragana: 'わたします', Kanji: '渡します', Group: 'I', Meaning: 'Trao', Special: 'false' },
    { Hiragana: 'いいます', Kanji: '言います', Group: 'I', Meaning: 'Nói', Special: 'false' },
    { Hiragana: 'のります', Kanji: '乗ります', Group: 'I', Meaning: 'Lên xe', Special: 'false' },
    { Hiragana: 'のぼります', Kanji: '登ります', Group: 'I', Meaning: 'Leo trèo', Special: 'false' },
    { Hiragana: 'あります', Kanji: '有ります', Group: 'I', Meaning: 'Có', Special: 'false' },
    { Hiragana: 'もらいます', Kanji: '貰います', Group: 'I', Meaning: 'Nhận', Special: 'false' },
    { Hiragana: 'おきます', Kanji: '置きます', Group: 'I', Meaning: 'Đặt, để', Special: 'false' },
    { Hiragana: 'わかります', Kanji: '分かります', Group: 'I', Meaning: 'Hiểu', Special: 'false' },
    { Hiragana: 'やすみます', Kanji: '休みます', Group: 'I', Meaning: 'Nghỉ ngơi', Special: 'false' },
    { Hiragana: 'はたらきます', Kanji: '働きます', Group: 'I', Meaning: 'Làm việc', Special: 'false' },
    { Hiragana: 'かします', Kanji: '貸します', Group: 'I', Meaning: 'Cho mượn', Special: 'false' },
    { Hiragana: 'はいります', Kanji: '入ります', Group: 'I', Meaning: 'Bước vào', Special: 'false' },
    { Hiragana: 'けします', Kanji: '消します', Group: 'I', Meaning: 'Tắt, xóa, dập', Special: 'false' },
    { Hiragana: 'いそぎます', Kanji: '急ぎます', Group: 'I', Meaning: 'Vội vàng', Special: 'false' },
    { Hiragana: 'よびます', Kanji: '呼びます', Group: 'I', Meaning: 'Kêu gọi', Special: 'false' },
    { Hiragana: 'すわります', Kanji: '座ります', Group: 'I', Meaning: 'Ngồi xuống', Special: 'false' },
    { Hiragana: 'つかいます', Kanji: '使います', Group: 'I', Meaning: 'Sử dụng', Special: 'false' },
    { Hiragana: 'ふります', Kanji: '降ります', Group: 'I', Meaning: 'Rơi (Mưa, tuyết)', Special: 'false' },
    { Hiragana: 'さきます', Kanji: '咲きます', Group: 'I', Meaning: 'Nở (Hoa)', Special: 'false' },
    { Hiragana: 'あるきます', Kanji: '歩きます', Group: 'I', Meaning: 'Đi bộ', Special: 'false' },
    { Hiragana: 'わたります', Kanji: '渡ります', Group: 'I', Meaning: 'Băng qua', Special: 'false' },
    { Hiragana: 'すみます', Kanji: '住みます', Group: 'I', Meaning: 'Sống, cư trú', Special: 'false' },
    { Hiragana: 'くもります', Kanji: '曇ります', Group: 'I', Meaning: 'Trời nhiều mây', Special: 'false' },
    { Hiragana: 'つもります', Kanji: '積もります', Group: 'I', Meaning: 'Chất đống', Special: 'false' },
    { Hiragana: 'ふきます', Kanji: '吹きます', Group: 'I', Meaning: 'Thổi (Gió)', Special: 'false' },
    { Hiragana: 'やみます', Kanji: '止みます', Group: 'I', Meaning: 'Ngừng, tạnh', Special: 'false' },

    { Hiragana: 'うたいます', Kanji: '歌います', Group: 'I', Meaning: 'Hát', Special: 'false' },
    { Hiragana: 'おどります', Kanji: '踊ります', Group: 'I', Meaning: 'Nhảy múa', Special: 'false' },
    { Hiragana: 'えらびます', Kanji: '選びます', Group: 'I', Meaning: 'Lựa chọn', Special: 'false' },
    { Hiragana: 'はらいます', Kanji: '払います', Group: 'I', Meaning: 'Trả tiền', Special: 'false' },
    { Hiragana: 'うります', Kanji: '売ります', Group: 'I', Meaning: 'Bán', Special: 'false' },
    { Hiragana: 'おくります', Kanji: '送ります', Group: 'I', Meaning: 'Gửi', Special: 'false' },
    { Hiragana: 'かちます', Kanji: '勝ちます', Group: 'I', Meaning: 'Thắng', Special: 'false' },
    { Hiragana: 'おします', Kanji: '押します', Group: 'I', Meaning: 'Ấn, đẩy', Special: 'false' },
    { Hiragana: 'ひきます', Kanji: '引きます', Group: 'I', Meaning: 'Kéo', Special: 'false' },
    { Hiragana: 'ならいます', Kanji: '習います', Group: 'I', Meaning: 'Học (từ ai đó)', Special: 'false' },
    { Hiragana: 'なおします', Kanji: '直します', Group: 'I', Meaning: 'Sửa chữa', Special: 'false' },
    { Hiragana: 'はこびます', Kanji: '運びます', Group: 'I', Meaning: 'Vận chuyển', Special: 'false' },
    { Hiragana: 'しります', Kanji: '知ります', Group: 'I', Meaning: 'Biết', Special: 'false' },
    { Hiragana: 'へります', Kanji: '減ります', Group: 'I', Meaning: 'Giảm xuống', Special: 'false' },
    { Hiragana: 'きります', Kanji: '切ります', Group: 'I', Meaning: 'Cắt', Special: 'false' },
    { Hiragana: 'つづきます', Kanji: '続きます', Group: 'I', Meaning: 'Tiếp tục', Special: 'false' },


    //「え」ます、Một âm tiết
    { Hiragana: 'たべます', Kanji: '食べます', Group: 'II', Meaning: 'Ăn', Special: 'false' },
    { Hiragana: 'かけます', Kanji: '掛けます', Group: 'II', Meaning: 'Gọi điện, đeo (Kính)', Special: 'false' },
    { Hiragana: 'あげます', Kanji: '上げます', Group: 'II', Meaning: 'Tặng', Special: 'false' },
    { Hiragana: 'つけます', Kanji: '付けます', Group: 'II', Meaning: 'Bật, gắn vào', Special: 'false' },
    { Hiragana: 'あけます', Kanji: '開けます', Group: 'II', Meaning: 'Mở ra', Special: 'false' },
    { Hiragana: 'しめます', Kanji: '閉めます', Group: 'II', Meaning: 'Đóng lại', Special: 'false' },
    { Hiragana: 'みせます', Kanji: '見せます', Group: 'II', Meaning: 'Cho xem', Special: 'false' },
    { Hiragana: 'はれます', Kanji: '晴れます', Group: 'II', Meaning: 'Trời quang đãng', Special: 'false' },
    { Hiragana: 'おしえます', Kanji: '教えます', Group: 'II', Meaning: 'Dạy, hướng dẫn', Special: 'false' },
    { Hiragana: 'でかけます', Kanji: '出掛けます', Group: 'II', Meaning: 'Ra ngoài', Special: 'false' },
    { Hiragana: 'でます', Kanji: '出ます', Group: 'II', Meaning: 'Ra ngoài', Special: 'false' },
    { Hiragana: 'ねます', Kanji: '寝ます', Group: 'II', Meaning: 'Ngủ', Special: 'false' },
    { Hiragana: 'みます', Kanji: '見ます', Group: 'II', Meaning: 'Nhìn', Special: 'false' },
    { Hiragana: 'きます', Kanji: '着ます', Group: 'II', Meaning: 'Mặc', Special: 'false' },
    { Hiragana: 'います', Kanji: '居ます', Group: 'II', Meaning: 'Có', Special: 'false' },

    { Hiragana: 'おきます', Kanji: '起きます', Group: 'II', Meaning: 'Thức dậy', Special: 'true' },
    { Hiragana: 'おります', Kanji: '降ります', Group: 'II', Meaning: 'Xuống', Special: 'true' },
    { Hiragana: 'あびます', Kanji: '浴びます', Group: 'II', Meaning: 'Tắm', Special: 'true' },
    { Hiragana: 'おちます', Kanji: '落ちます', Group: 'II', Meaning: 'Rơi', Special: 'true' },
    { Hiragana: 'できます', Kanji: '出来ます', Group: 'II', Meaning: 'Có thể', Special: 'true' },////////////////////////////////////////////////////////////////////
    { Hiragana: 'かります', Kanji: '借ります', Group: 'II', Meaning: 'Mượn', Special: 'true' },
    { Hiragana: 'しんじます', Kanji: '信じます', Group: 'II', Meaning: 'Tin tưởng', Special: 'true' },

    { Hiragana: 'ふえます', Kanji: '増えます', Group: 'II', Meaning: 'Tăng lên', Special: 'false' },
    { Hiragana: 'まけます', Kanji: '負けます', Group: 'II', Meaning: 'Thua', Special: 'false' },
    { Hiragana: 'すてます', Kanji: '捨てます', Group: 'II', Meaning: 'Vứt bỏ', Special: 'false' },
    { Hiragana: 'はじめます', Kanji: '始めます', Group: 'II', Meaning: 'Bắt đầu', Special: 'false' },
    { Hiragana: 'つづけます', Kanji: '続けます', Group: 'II', Meaning: 'Tiếp tục', Special: 'false' },
    { Hiragana: 'くらべます', Kanji: '比べます', Group: 'II', Meaning: 'So sánh', Special: 'false' },
    { Hiragana: 'わすれます', Kanji: '忘れます', Group: 'II', Meaning: 'Quên', Special: 'false' },
    { Hiragana: 'おぼえます', Kanji: '覚えます', Group: 'II', Meaning: 'Ghi nhớ', Special: 'false' },
    { Hiragana: 'きめます', Kanji: '決めます', Group: 'II', Meaning: 'Quyết định', Special: 'false' },
    { Hiragana: 'ながれます', Kanji: '流れます', Group: 'II', Meaning: 'Chảy (nước, thời gian)', Special: 'false' },
    { Hiragana: 'むかえます', Kanji: '迎えます', Group: 'II', Meaning: 'Đón', Special: 'false' },
    { Hiragana: 'たおれます', Kanji: '倒れます', Group: 'II', Meaning: 'Đổ, ngã', Special: 'false' },
    { Hiragana: 'やめます', Kanji: '止めます', Group: 'II', Meaning: 'Dừng, bỏ (hành động)', Special: 'false' },


    //N＋します => Danh động từ
    { Hiragana: 'きます', Kanji: '来ます', Group: 'III', Meaning: 'Đến', Special: 'true' },
    { Hiragana: 'します', Kanji: 'します', Group: 'III', Meaning: 'Làm', Special: 'false' },
    { Hiragana: 'べんきょうします', Kanji: '勉強します', Group: 'III', Meaning: 'Học', Special: 'false' },
    { Hiragana: 'せんたくします', Kanji: '洗濯します', Group: 'III', Meaning: 'Giặt', Special: 'false' },
    { Hiragana: 'そうじします', Kanji: '掃除します', Group: 'III', Meaning: 'Làm việc nhà', Special: 'false' },
    { Hiragana: 'しょくじします', Kanji: '食事します', Group: 'III', Meaning: 'Dùng bữa', Special: 'false' },
    { Hiragana: 'コピーします', Kanji: 'コピーします', Group: 'III', Meaning: 'Sao chép', Special: 'false' },
];

export const Family = [
    { Word: 'NoFamily', Hiragana: 'そふ', Meaning: 'Ông' },
    { Word: 'NoFamily', Hiragana: 'そぼ', Meaning: 'Bà' },
    { Word: 'NoFamily', Hiragana: 'ちち', Meaning: 'Bố' },
    { Word: 'NoFamily', Hiragana: 'はは', Meaning: 'Mẹ' },
    { Word: 'NoFamily', Hiragana: 'おば', Meaning: 'Cô' },
    { Word: 'NoFamily', Hiragana: 'おじ', Meaning: 'Chú' },
    { Word: 'NoFamily', Hiragana: 'あに', Meaning: 'Anh trai' },
    { Word: 'NoFamily', Hiragana: 'あね', Meaning: 'Chị gái' },
    { Word: 'NoFamily', Hiragana: 'おとうと', Meaning: 'Em trai' },
    { Word: 'NoFamily', Hiragana: 'いもうと', Meaning: 'Em gái' },

    { Word: 'NoFamily', Hiragana: 'おじいさん', Meaning: 'Ông người khác' },
    { Word: 'NoFamily', Hiragana: 'おばあさん', Meaning: 'Bà người khác' },
    { Word: 'NoFamily', Hiragana: 'おとうさん', Meaning: 'Bố người khác' },
    { Word: 'NoFamily', Hiragana: 'おかあさん', Meaning: 'Mẹ người khác' },
    { Word: 'NoFamily', Hiragana: 'おばさん', Meaning: 'Cô người khác' },
    { Word: 'NoFamily', Hiragana: 'おじさん', Meaning: 'Chú người khác' },
    { Word: 'NoFamily', Hiragana: 'おにいさん', Meaning: 'Anh trai người khác' },
    { Word: 'NoFamily', Hiragana: 'おねえさん', Meaning: 'Chị gái người khác' },
    { Word: 'NoFamily', Hiragana: 'おとうとさん', Meaning: 'Em trai người khác' },
    { Word: 'NoFamily', Hiragana: 'いもうとさん', Meaning: 'Em gái người khác' },

    { Word: 'NoFamily', Hiragana: 'おっと', Meaning: 'Chồng' },
    { Word: 'NoFamily', Hiragana: 'つま', Meaning: 'Vợ' },
    { Word: 'NoFamily', Hiragana: 'むすこ', Meaning: 'Con trai' },
    { Word: 'NoFamily', Hiragana: 'むすめ', Meaning: 'Con gái' },

    { Word: 'NoFamily', Hiragana: 'ごしゅじん', Meaning: 'Chồng người khác' },
    { Word: 'NoFamily', Hiragana: 'おくさん', Meaning: 'Vợ người khác' },
    { Word: 'NoFamily', Hiragana: 'むすこさん', Meaning: 'Con trai người khác' },
    { Word: 'NoFamily', Hiragana: 'むすめさん', Meaning: 'Con gái người khác' },

    { Word: 'NoFamily', Hiragana: 'りょうしん', Meaning: 'Ba mẹ' },
    { Word: 'NoFamily', Hiragana: 'しんせき', Meaning: 'Họ hàng' },
    { Word: 'NoFamily', Hiragana: 'きょうだい', Meaning: 'Anh chị em ruột' },
    { Word: 'NoFamily', Hiragana: 'こども', Meaning: 'Con nít' },
    { Word: 'NoFamily', Hiragana: 'おこさん', Meaning: 'Con nhà người khác' },

    { Word: 'NoFamily', Hiragana: 'NoFamily', Meaning: 'NoFamily' },
    { Word: 'NoFamily', Hiragana: 'NoFamily', Meaning: 'NoFamily' },

    { Word: 'NoFamily', Hiragana: 'NoFamily', Meaning: 'NoFamily' },
    { Word: 'NoFamily', Hiragana: 'NoFamily', Meaning: 'NoFamily' },
];
