export const Verb = [
    { Verb: 'NoVerb', Kanji: 'NoVerb', Group: 'NoVerb', Meaning: 'NoVerb', Romaji: 'NoVerb' },

    //「い」ます
    { Verb: 'いきます', Kanji: '行きます', Group: 'I', Meaning: 'Đi', Romaji: 'ikimasu' },
    { Verb: 'あいます', Kanji: '会います', Group: 'I', Meaning: 'Gặp', Romaji: 'aimasu' },
    { Verb: 'のみます', Kanji: '飲みます', Group: 'I', Meaning: 'Uống', Romaji: 'nomimasu' },
    { Verb: 'とります', Kanji: '取ります', Group: 'I', Meaning: 'Lấy', Romaji: 'torimasu' },
    { Verb: 'かいます', Kanji: '買います', Group: 'I', Meaning: 'Mua', Romaji: 'kaimasu' },
    { Verb: 'もちます', Kanji: '持ちます', Group: 'I', Meaning: 'Cầm nắm', Romaji: 'mochimasu' },
    { Verb: 'まちます', Kanji: '待ちます', Group: 'I', Meaning: 'Chờ', Romaji: 'machimasu' },
    { Verb: 'とまります', Kanji: '止まります', Group: 'I', Meaning: 'Dừng lại', Romaji: 'tomarimasu' },
    { Verb: 'かえります', Kanji: '帰ります', Group: 'I', Meaning: 'Về', Romaji: 'kaerimasu' },
    { Verb: 'よみます', Kanji: '読みます', Group: 'I', Meaning: 'Đọc', Romaji: 'yomimasu' },
    { Verb: 'あそびます', Kanji: '遊びます', Group: 'I', Meaning: 'Đi chơi', Romaji: 'asobimasu' },
    { Verb: 'しにます', Kanji: '死にます', Group: 'I', Meaning: 'Chết', Romaji: 'shinimasu' },
    { Verb: 'かきます', Kanji: '書きます', Group: 'I', Meaning: 'Viết', Romaji: 'kakimasu' },
    { Verb: 'ききます', Kanji: '聞きます', Group: 'I', Meaning: 'Nghe, hỏi', Romaji: 'kikimasu' },
    { Verb: 'およぎます', Kanji: '泳ぎます', Group: 'I', Meaning: 'Bơi', Romaji: 'oyogimasu' },
    { Verb: 'はなします', Kanji: '話します', Group: 'I', Meaning: 'Nói chuyện', Romaji: 'hanashimasu' },
    { Verb: 'わたします', Kanji: '渡します', Group: 'I', Meaning: 'Trao', Romaji: 'watashimasu' },
    { Verb: 'いいます', Kanji: '言います', Group: 'I', Meaning: 'Nói', Romaji: 'iimasu' },
    { Verb: 'のります', Kanji: '乗ります', Group: 'I', Meaning: 'Lên xe', Romaji: 'norimasu' },
    { Verb: 'のぼります', Kanji: '登ります', Group: 'I', Meaning: 'Leo trèo', Romaji: 'noborimasu' },
    { Verb: 'あります', Kanji: '有ります', Group: 'I', Meaning: 'Có', Romaji: 'arimasu' },
    { Verb: 'もらいます', Kanji: '貰います', Group: 'I', Meaning: 'Nhận', Romaji: 'moraimasu' },
    { Verb: 'おきます', Kanji: '置きます', Group: 'I', Meaning: 'Đặt, để', Romaji: 'okimasu' },
    { Verb: 'わかります', Kanji: '分かります', Group: 'I', Meaning: 'Hiểu', Romaji: 'wakarimasu' },
    { Verb: 'やすみます', Kanji: '休みます', Group: 'I', Meaning: 'Nghỉ ngơi', Romaji: 'yasumimasu' },
    { Verb: 'はたらきます', Kanji: '働きます', Group: 'I', Meaning: 'Làm việc', Romaji: 'hatarakimasu' },
    { Verb: 'かします', Kanji: '貸します', Group: 'I', Meaning: 'Cho mượn', Romaji: 'kashimasu' },
    { Verb: 'はいります', Kanji: '入ります', Group: 'I', Meaning: 'Bước vào', Romaji: 'hairimasu' },
    { Verb: 'けします', Kanji: '消します', Group: 'I', Meaning: 'Tắt, xóa, dập', Romaji: 'keshimasu' },
    { Verb: 'いそぎます', Kanji: '急ぎます', Group: 'I', Meaning: 'Vội vàng', Romaji: 'isogimasu' },
    { Verb: 'よびます', Kanji: '呼びます', Group: 'I', Meaning: 'Kêu gọi', Romaji: 'yobimasu' },
    { Verb: 'すわります', Kanji: '座ります', Group: 'I', Meaning: 'Ngồi xuống', Romaji: 'suwarimasu' },
    { Verb: 'つかいます', Kanji: '使います', Group: 'I', Meaning: 'Sử dụng', Romaji: 'tsukaimasu' },
    { Verb: 'ふります', Kanji: '降ります', Group: 'I', Meaning: 'Rơi (Mưa, tuyết)', Romaji: 'furimasu' },
    { Verb: 'さきます', Kanji: '咲きます', Group: 'I', Meaning: 'Nở (Hoa)', Romaji: 'sakimasu' },
    { Verb: 'あるきます', Kanji: '歩きます', Group: 'I', Meaning: 'Đi bộ', Romaji: 'arukimasu' },
    { Verb: 'わたります', Kanji: '渡ります', Group: 'I', Meaning: 'Băng qua', Romaji: 'watarimasu' },
    { Verb: 'すみます', Kanji: '住みます', Group: 'I', Meaning: 'Sống, cư trú', Romaji: 'sumimasu' },
    { Verb: 'くもります', Kanji: '曇ります', Group: 'I', Meaning: 'Trời nhiều mây', Romaji: 'kumorimasu' },
    { Verb: 'つもります', Kanji: '積もります', Group: 'I', Meaning: 'Chất đống', Romaji: 'tsumorimasu' },
    { Verb: 'ふきます', Kanji: '吹きます', Group: 'I', Meaning: 'Thổi (Gió)', Romaji: 'fukimasu' },
    { Verb: 'やみます', Kanji: '止みます', Group: 'I', Meaning: 'Ngừng, tạnh', Romaji: 'yamimasu' },


    //「え」ます、Một âm tiết
    { Verb: 'たべます', Kanji: '食べます', Group: 'II', Meaning: 'Ăn', Romaji: 'tabemasu' },
    { Verb: 'かけます', Kanji: '掛けます', Group: 'II', Meaning: 'Đeo (Kính)', Romaji: 'kakemasu' },
    { Verb: 'かけます', Kanji: '掛けます', Group: 'II', Meaning: 'Gọi điện', Romaji: 'kakemasu' },
    { Verb: 'あげます', Kanji: '上げます', Group: 'II', Meaning: 'Tặng', Romaji: 'agemasu' },
    { Verb: 'つけます', Kanji: '付けます', Group: 'II', Meaning: 'Bật, gắn vào', Romaji: 'tsukemasu' },
    { Verb: 'あけます', Kanji: '開けます', Group: 'II', Meaning: 'Mở ra', Romaji: 'akemasu' },
    { Verb: 'しめます', Kanji: '閉めます', Group: 'II', Meaning: 'Đóng lại', Romaji: 'shimemasu' },
    { Verb: 'みせます', Kanji: '見せます', Group: 'II', Meaning: 'Cho xem', Romaji: 'misemasu' },
    { Verb: 'はれます', Kanji: '晴れます', Group: 'II', Meaning: 'Trời quang đãng', Romaji: 'haremasu' },
    { Verb: 'おしえます', Kanji: '教えます', Group: 'II', Meaning: 'Dạy, hướng dẫn', Romaji: 'oshiemasu' },
    { Verb: 'でかけます', Kanji: '出掛けます', Group: 'II', Meaning: 'Ra ngoài', Romaji: 'dekakemasu' },
    { Verb: 'でます', Kanji: '出ます', Group: 'II', Meaning: 'Ra ngoài', Romaji: 'demasu' },
    { Verb: 'ねます', Kanji: '寝ます', Group: 'II', Meaning: 'Ngủ', Romaji: 'nemasu' },
    { Verb: 'みます', Kanji: '見ます', Group: 'II', Meaning: 'Nhìn', Romaji: 'mimasu' },
    { Verb: 'きます', Kanji: '着ます', Group: 'II', Meaning: 'Mặc', Romaji: 'kimasu' },
    { Verb: 'います', Kanji: '居ます', Group: 'II', Meaning: 'Có', Romaji: 'imasu' },

    { Verb: 'おきます', Kanji: '起きます', Group: 'II', Meaning: 'Thức dậy', Romaji: 'okimasu' },
    { Verb: 'おります', Kanji: '降ります', Group: 'II', Meaning: 'Xuống', Romaji: 'orimasu' },
    { Verb: 'あびます', Kanji: '浴びます', Group: 'II', Meaning: 'Tắm', Romaji: 'abimasu' },
    { Verb: 'おちます', Kanji: '落ちます', Group: 'II', Meaning: 'Rơi', Romaji: 'ochimasu' },
    { Verb: 'できます', Kanji: '出来ます', Group: 'II', Meaning: 'Có thể', Romaji: 'dekimasu' },
    { Verb: 'かります', Kanji: '借ります', Group: 'II', Meaning: 'Mượn', Romaji: 'karimasu' },
    { Verb: 'つづきます', Kanji: '続きます', Group: 'II', Meaning: 'Tiếp tục', Romaji: 'tsugimasu' },
    { Verb: 'しんじます', Kanji: '信じます', Group: 'II', Meaning: 'Tin tưởng', Romaji: 'shinjimasu' },


    //N＋します => Danh động từ
    { Verb: 'きます', Kanji: '来ます', Group: 'III', Meaning: 'Đến', Romaji: 'kimasu' },
    { Verb: 'します', Kanji: 'します', Group: 'III', Meaning: 'Làm', Romaji: 'shimasu' },
    { Verb: 'べんきょうします', Kanji: '勉強します', Group: 'III', Meaning: 'Học', Romaji: 'benkyoushimasu' },
    { Verb: 'せんたくします', Kanji: '洗濯します', Group: 'III', Meaning: 'Giặt', Romaji: 'sentakushimasu' },
    { Verb: 'そうじします', Kanji: '掃除します', Group: 'III', Meaning: 'Làm việc nhà', Romaji: 'soujishimasu' },
    { Verb: 'しょくじします', Kanji: '食事します', Group: 'III', Meaning: 'Dùng bữa', Romaji: 'shokujishimasu' },
    { Verb: 'コピーします', Kanji: 'コピーします', Group: 'III', Meaning: 'Sao chép', Romaji: 'kopiishimasu' },
];